// Generated by scripts/build-dardani-assets.py from dardani-assets/asset-map.json.
// Do not edit by hand: re-run the script. Components look the mascot up by
// name here and never hard-code a /mascot path.

export type DardaniStillName = "airport" | "avatar-happy" | "avatar-neutral" | "avatar-talking" | "avatar-thinking" | "bell" | "celebrating" | "diaspora" | "empty" | "error-404" | "exchange" | "explaining" | "face-confused" | "face-laughing" | "face-sad" | "face-surprised" | "face-wink" | "flag-albania" | "flag-kosovo" | "flying" | "flying-news" | "fuel" | "idle" | "key" | "matchday-scarf" | "new-year" | "offline" | "reading" | "researching" | "running" | "sleeping" | "sorry" | "standing-alt" | "streak" | "thinking-bubble" | "toni" | "tregu-explainer" | "tregu-lose" | "tregu-portfolio" | "tregu-predict" | "tregu-win" | "wave" | "weather";

export type DardaniLoopName = "bell" | "explaining" | "explaining-news" | "flying" | "flying-news" | "greeting" | "headbob" | "idle" | "reading" | "researching" | "running" | "sleeping" | "thinking-bubble" | "tregu-explainer";

export type DardaniStill = {
  src: string;
  width: number;
  height: number;
  /** Albanian alt text. */
  alt: string;
  /** Suggested Albanian copy for the surface it belongs to, when the map gives one. */
  copy: string | null;
};

export type DardaniLoop = {
  webm: string;
  mp4: string;
  /** Stacked-alpha MP4 (colour above, alpha below) that the site plays through WebGL. */
  stack: string;
  /** The loop's own first frame: the poster, and the reduced-motion image. */
  poster: string;
  width: number;
  height: number;
  alt: string;
};

export const DARDANI_STILLS: Record<DardaniStillName, DardaniStill> = {
  "airport": { src: "/mascot/dardani-airport.webp", width: 332, height: 480, alt: "Dardani shikon orën pranë valixhes", copy: null },
  "avatar-happy": { src: "/mascot/dardani-avatar-happy.webp", width: 160, height: 159, alt: "Dardani i gëzuar", copy: null },
  "avatar-neutral": { src: "/mascot/dardani-avatar-neutral.webp", width: 147, height: 160, alt: "Dardani, i qetë dhe i buzëqeshur", copy: null },
  "avatar-talking": { src: "/mascot/dardani-avatar-talking.webp", width: 143, height: 160, alt: "Dardani duke folur", copy: null },
  "avatar-thinking": { src: "/mascot/dardani-avatar-thinking.webp", width: 140, height: 160, alt: "Dardani me krah në mjekër, duke menduar", copy: null },
  "bell": { src: "/mascot/dardani-bell.webp", width: 386, height: 480, alt: "Dardani i bie ziles", copy: "Të njoftoj kur ka lajme të mëdha?" },
  "celebrating": { src: "/mascot/dardani-celebrating.webp", width: 532, height: 720, alt: "Dardani feston me krahë lart", copy: null },
  "diaspora": { src: "/mascot/dardani-diaspora.webp", width: 493, height: 480, alt: "Dardani me valixhe dhe pasaportë", copy: "Mirë se erdhe në shtëpi" },
  "empty": { src: "/mascot/dardani-empty.webp", width: 488, height: 480, alt: "Dardani shikon në një kuti bosh", copy: "Ende asgjë këtu" },
  "error-404": { src: "/mascot/dardani-error-404.webp", width: 289, height: 480, alt: "Dardani mban një gazetë të grisur", copy: "Kjo faqe nuk u gjet" },
  "exchange": { src: "/mascot/dardani-exchange.webp", width: 512, height: 410, alt: "Dardani me dy monedha që këmbehen", copy: null },
  "explaining": { src: "/mascot/dardani-explaining.webp", width: 345, height: 480, alt: "Dardani shpjegon", copy: null },
  "face-confused": { src: "/mascot/dardani-face-confused.webp", width: 147, height: 160, alt: "Dardani i hutuar, me kokë anash", copy: null },
  "face-laughing": { src: "/mascot/dardani-face-laughing.webp", width: 151, height: 160, alt: "Dardani qesh", copy: null },
  "face-sad": { src: "/mascot/dardani-face-sad.webp", width: 144, height: 160, alt: "Dardani i trishtuar", copy: null },
  "face-surprised": { src: "/mascot/dardani-face-surprised.webp", width: 144, height: 160, alt: "Dardani i habitur", copy: null },
  "face-wink": { src: "/mascot/dardani-face-wink.webp", width: 147, height: 160, alt: "Dardani shkel syrin", copy: null },
  "flag-albania": { src: "/mascot/dardani-flag-albania.webp", width: 277, height: 480, alt: "Dardani valëvit flamurin shqiptar", copy: "Gëzuar Ditën e Flamurit!" },
  "flag-kosovo": { src: "/mascot/dardani-flag-kosovo.webp", width: 287, height: 480, alt: "Dardani valëvit flamurin e Kosovës", copy: "Gëzuar Ditën e Pavarësisë!" },
  "flying": { src: "/mascot/dardani-flying.webp", width: 512, height: 369, alt: "Dardani fluturon", copy: null },
  "flying-news": { src: "/mascot/dardani-flying-news.webp", width: 512, height: 413, alt: "Dardani fluturon me gazetë", copy: null },
  "fuel": { src: "/mascot/dardani-fuel.webp", width: 306, height: 480, alt: "Dardani mban pistoletën e karburantit", copy: null },
  "idle": { src: "/mascot/dardani-idle.webp", width: 280, height: 480, alt: "Dardani qëndron i qetë", copy: null },
  "key": { src: "/mascot/dardani-key.webp", width: 288, height: 480, alt: "Dardani mban një çelës të artë", copy: "Hyr në llogari" },
  "matchday-scarf": { src: "/mascot/dardani-matchday-scarf.webp", width: 429, height: 480, alt: "Dardani ngre shallin blu e të verdhë", copy: "Hajde Dardanët!" },
  "new-year": { src: "/mascot/dardani-new-year.webp", width: 399, height: 480, alt: "Dardani me kapelë feste dhe konfeti", copy: "Gëzuar Vitin e Ri!" },
  "offline": { src: "/mascot/dardani-offline.webp", width: 454, height: 480, alt: "Dardani mban dy skajet e një kablloje të shkëputur", copy: "S'ka lidhje me internetin" },
  "reading": { src: "/mascot/dardani-reading.webp", width: 313, height: 480, alt: "Dardani lexon një libër", copy: null },
  "researching": { src: "/mascot/dardani-researching.webp", width: 314, height: 480, alt: "Dardani me xhami zmadhues", copy: null },
  "running": { src: "/mascot/dardani-running.webp", width: 493, height: 480, alt: "Dardani vrapon", copy: null },
  "sleeping": { src: "/mascot/dardani-sleeping.webp", width: 350, height: 480, alt: "Dardani fle me kapuç gjumi", copy: "Asnjë lajm i ri tani për tani" },
  "sorry": { src: "/mascot/dardani-sorry.webp", width: 376, height: 480, alt: "Dardani kruan kokën me një çelës anglez në dorë", copy: "Diçka shkoi keq, po e rregullojmë" },
  "standing-alt": { src: "/mascot/dardani-standing-alt.webp", width: 342, height: 480, alt: "Dardani qëndron me gazetë nën krah", copy: null },
  "streak": { src: "/mascot/dardani-streak.webp", width: 508, height: 480, alt: "Dardani me kalendar dhe flakë", copy: "3 ditë rresht!" },
  "thinking-bubble": { src: "/mascot/dardani-thinking-bubble.webp", width: 219, height: 480, alt: "Dardani mendon", copy: null },
  "toni": { src: "/mascot/dardani-toni.webp", width: 327, height: 480, alt: "Dardani me glob dhe xhami zmadhues", copy: "Toni i botës për Kosovën" },
  "tregu-explainer": { src: "/mascot/dardani-tregu-explainer.webp", width: 512, height: 373, alt: "Dardani pranë një grafiku në rritje", copy: "Si funksionon Tregu" },
  "tregu-lose": { src: "/mascot/dardani-tregu-lose.webp", width: 418, height: 480, alt: "Dardani ngre supet butësisht", copy: "Kësaj radhe jo" },
  "tregu-portfolio": { src: "/mascot/dardani-tregu-portfolio.webp", width: 294, height: 480, alt: "Dardani mban një portofol me monedha", copy: "Portofoli im" },
  "tregu-predict": { src: "/mascot/dardani-tregu-predict.webp", width: 424, height: 480, alt: "Dardani shtyp butonin jeshil pranë atij të kuq", copy: "Bëj parashikimin tënd" },
  "tregu-win": { src: "/mascot/dardani-tregu-win.webp", width: 391, height: 480, alt: "Dardani ngre një trofe të artë", copy: "E qëllove!" },
  "wave": { src: "/mascot/dardani-wave.webp", width: 355, height: 480, alt: "Dardani përshëndet me krah", copy: null },
  "weather": { src: "/mascot/dardani-weather.webp", width: 363, height: 480, alt: "Dardani me ombrellë", copy: null },
};

export const DARDANI_LOOPS: Record<DardaniLoopName, DardaniLoop> = {
  "bell": { webm: "/mascot/dardani-bell.webm", mp4: "/mascot/dardani-bell.mp4", stack: "/mascot/dardani-bell-stack.mp4", poster: "/mascot/dardani-bell-poster.webp", width: 480, height: 640, alt: "Dardani i bie ziles" },
  "explaining": { webm: "/mascot/dardani-explaining.webm", mp4: "/mascot/dardani-explaining.mp4", stack: "/mascot/dardani-explaining-stack.mp4", poster: "/mascot/dardani-explaining-poster.webp", width: 480, height: 640, alt: "Dardani shpjegon një veçori me krahë" },
  "explaining-news": { webm: "/mascot/dardani-explaining-news.webm", mp4: "/mascot/dardani-explaining-news.mp4", stack: "/mascot/dardani-explaining-news-stack.mp4", poster: "/mascot/dardani-explaining-news-poster.webp", width: 480, height: 640, alt: "Dardani tregon lajmin dhe e shpjegon" },
  "flying": { webm: "/mascot/dardani-flying.webm", mp4: "/mascot/dardani-flying.mp4", stack: "/mascot/dardani-flying-stack.mp4", poster: "/mascot/dardani-flying-poster.webp", width: 480, height: 360, alt: "Dardani fluturon në vend" },
  "flying-news": { webm: "/mascot/dardani-flying-news.webm", mp4: "/mascot/dardani-flying-news.mp4", stack: "/mascot/dardani-flying-news-stack.mp4", poster: "/mascot/dardani-flying-news-poster.webp", width: 480, height: 360, alt: "Dardani fluturon me një gazetë në kthetra" },
  "greeting": { webm: "/mascot/dardani-greeting.webm", mp4: "/mascot/dardani-greeting.mp4", stack: "/mascot/dardani-greeting-stack.mp4", poster: "/mascot/dardani-greeting-poster.webp", width: 480, height: 640, alt: "Dardani përshëndet me krah" },
  "headbob": { webm: "/mascot/dardani-headbob.webm", mp4: "/mascot/dardani-headbob.mp4", stack: "/mascot/dardani-headbob-stack.mp4", poster: "/mascot/dardani-headbob-poster.webp", width: 160, height: 160, alt: "Dardani lëkund kokën" },
  "idle": { webm: "/mascot/dardani-idle.webm", mp4: "/mascot/dardani-idle.mp4", stack: "/mascot/dardani-idle-stack.mp4", poster: "/mascot/dardani-idle-poster.webp", width: 480, height: 640, alt: "Dardani merr frymë qetë dhe pulit sytë" },
  "reading": { webm: "/mascot/dardani-reading.webm", mp4: "/mascot/dardani-reading.mp4", stack: "/mascot/dardani-reading-stack.mp4", poster: "/mascot/dardani-reading-poster.webp", width: 480, height: 640, alt: "Dardani lexon dhe analizon një libër" },
  "researching": { webm: "/mascot/dardani-researching.webm", mp4: "/mascot/dardani-researching.mp4", stack: "/mascot/dardani-researching-stack.mp4", poster: "/mascot/dardani-researching-poster.webp", width: 480, height: 640, alt: "Dardani kërkon me xhami zmadhues" },
  "running": { webm: "/mascot/dardani-running.webm", mp4: "/mascot/dardani-running.mp4", stack: "/mascot/dardani-running-stack.mp4", poster: "/mascot/dardani-running-poster.webp", width: 480, height: 360, alt: "Dardani vrapon ndërsa faqja ngarkohet" },
  "sleeping": { webm: "/mascot/dardani-sleeping.webm", mp4: "/mascot/dardani-sleeping.mp4", stack: "/mascot/dardani-sleeping-stack.mp4", poster: "/mascot/dardani-sleeping-poster.webp", width: 480, height: 640, alt: "Dardani fle me kapuç gjumi" },
  "thinking-bubble": { webm: "/mascot/dardani-thinking-bubble.webm", mp4: "/mascot/dardani-thinking-bubble.mp4", stack: "/mascot/dardani-thinking-bubble-stack.mp4", poster: "/mascot/dardani-thinking-bubble-poster.webp", width: 480, height: 640, alt: "Dardani mendon, me flluskë mendimi mbi kokë" },
  "tregu-explainer": { webm: "/mascot/dardani-tregu-explainer.webm", mp4: "/mascot/dardani-tregu-explainer.mp4", stack: "/mascot/dardani-tregu-explainer-stack.mp4", poster: "/mascot/dardani-tregu-explainer-poster.webp", width: 480, height: 360, alt: "Dardani shpjegon grafikun e Tregut" },
};
