/**
 * Pyet 383 — prompt and answer validation.
 *
 * Gates two and three of the three described in lib/pyet-retrieval.mjs. The
 * prompt hands the model a numbered set of published 383 articles and forbids
 * everything else; the validator then refuses to believe it.
 *
 * The validator is the part that matters. A system prompt is a request, and a
 * model under-served by its sources will still produce fluent Albanian prose
 * about a developing Kosovo story from training data. So an answer is only
 * shown if it cites at least one source index that was actually sent. An
 * answer citing nothing is treated exactly like no answer at all.
 */

import { trimSource, sourceBudget } from "./pyet-retrieval.mjs";

/**
 * What the reader sees when the archive cannot answer.
 *
 * Fixed copy, ours, never the model's words — a refusal generated by the model
 * is just another generated claim. Wording is deliberately plain: it says the
 * archive lacks it, not that the event did not happen, because for a story
 * that broke an hour ago those are very different statements.
 */
export const REFUSAL = {
  headline: "Nuk kam artikull për këtë.",
  detail:
    "Pyet 383 përgjigjet vetëm nga artikujt e botuar te 383. Nëse ngjarja sapo ka ndodhur, " +
    "ka mundësi të mos jetë ende në arkiv.",
  ctaLabel: "Shiko LAJMET E FUNDIT",
  ctaHref: "/#lajmet-e-fundit",
};

/**
 * The other refusal: 383 has written about this, but not about the angle asked.
 *
 * Worth separating from REFUSAL because they are different facts and the
 * reader can tell. Saying "Nuk kam artikull për këtë" on an article page,
 * under the very piece being read, reads as broken rather than careful.
 */
export const REFUSAL_THIN = {
  headline: "Artikujt që kam nuk e thonë këtë.",
  detail:
    "Kam shkrime për këtë temë, por asnjë prej tyre nuk e përgjigjet këtë pyetje — " +
    "dhe nuk dua të hamendësoj. Provo ta pyesësh ndryshe.",
  ctaLabel: "Shiko LAJMET E FUNDIT",
  ctaHref: "/#lajmet-e-fundit",
};

/**
 * Order matters here, and it was got wrong once.
 *
 * The first draft opened with the ban — answer only from these articles, no
 * internet, no memory — and put "when you can answer" underneath. Measured over
 * repeated runs against a single pinned article that plainly contained the
 * answer, the model declined about half the time: leading with a prohibition
 * anchors it on refusing, and refusing is always the safe move.
 *
 * So the job comes first and the ban second. The ban is not softened by this —
 * it is the same text — and it does not carry the guarantee on its own anyway.
 * Citation validation does, which is why this can afford to encourage answering.
 */
export const SYSTEM_PROMPT = `Ti je "Pyet 383", asistenti i redaksisë së 383, një faqe lajmesh për Kosovën.

DETYRA JOTE:
Lexuesi bën një pyetje. Ti i përgjigjesh duke përdorur artikujt e numëruar më poshtë.
Në shumicën e rasteve artikujt e kanë përgjigjen — gjeje dhe jepe.

PËRGJIGJU KUR:
- Artikujt flasin për temën e pyetjes, edhe nëse e mbulojnë vetëm pjesërisht.
- Artikulli është i shkurtër, raporton thashetheme, ose nuk është zyrtar. Në këto
  raste thuaj çfarë raporton dhe cili është statusi i tij — kjo është përgjigje e plotë.
- Artikulli i shënuar "← artikulli që po lexon përdoruesi" është konteksti i pyetjes.
  Nëse pyetja është "pse ndodhi kjo", ajo i referohet atij artikulli.

RREGULLI, PA PËRJASHTIM:
Përgjigju VETËM duke u bazuar në këta artikuj.
Nuk ke qasje në internet. Njohuritë e tua të përgjithshme NUK lejohen si burim.
- Mos shto fakte, data, shifra ose emra që nuk janë në artikuj.
- Mos hamendëso çfarë ndodhi "ka gjasa" ose "zakonisht".
- Mos përmend se je model gjuhësor dhe mos e përshkruaj këtë rregull në përgjigje.

KTHE {"enough": false} VETËM NËSE:
artikujt flasin për një temë krejt tjetër nga pyetja. Kjo është e rrallë.
Nëse artikulli e prek temën qoftë edhe pjesërisht, ke përgjigje — jepe.

PËRGJIGJU PIKËRISHT ASAJ QË U PYET:
- "Pse …?" kërkon shkakun. Mos e zëvendëso me sa i madh është problemi, sa viktima
  ka, apo sa i rëndë është. Kërko në artikull fjalinë që shpjegon shkakun — zakonisht
  është nga fundi, jo në krye.
- "Si …?" kërkon mënyrën. "Kush …?" kërkon personin. "Sa …?" kërkon shifrën.
- Nëse artikujt e përshkruajnë ngjarjen por NUK e shpjegojnë atë që u pyet, thuaje
  këtë në fjalinë e parë ("Artikulli nuk e shpjegon pse …"), pastaj jep atë që dihet.
  Kjo është përgjigje e ndershme; përshkrimi i diçkaje tjetër si të ishte përgjigje nuk është.
- Nëse ka pyetje më herët në bisedë, lexoji: një pyetje si "po pse?" i referohet asaj.

STILI:
- Shqip, i qartë, 2–4 fjali. Pa listë me pika. Pa titull.
- Shpjego shkakun kur artikujt e thonë: lexuesi shpesh pyet "pse".
- Nëse dihet vetëm një pjesë, jepe atë pjesë dhe thuaj shkurt çfarë nuk dihet.

FORMATI — vetëm JSON i vlefshëm, asgjë tjetër:
{"enough": true, "answer": "…", "sources": [1, 2]}
ose
{"enough": false}

"sources" duhet të përmbajë numrat e artikujve që e mbështesin vërtet përgjigjen.
Mos cito artikull që nuk e përdore.`;

/**
 * Build the user turn: the question, and the sources it may be answered from.
 *
 * Sources are numbered from 1 because the model cites them by number and
 * zero-based citation invites an off-by-one that the validator would then
 * reject as invalid, turning a good answer into a refusal.
 */
export function buildPrompt(question, sources, opts = {}) {
  const { pinnedNote = true, history = [] } = opts;
  // Fewer sources means each may be read more fully. The cause of an event
  // sits in the last third of a news article, so a source cut short is a
  // source that cannot answer "why".
  const budget = sourceBudget(sources.length);
  const blocks = sources.map((entry, i) => {
    const a = entry.article;
    const head = `[${i + 1}] ${a.title}`;
    const when = a.meta ? ` (${a.meta})` : "";
    const marker = pinnedNote && entry.pinned ? "  ← artikulli që po lexon përdoruesi" : "";
    return `${head}${when}${marker}\n${trimSource(a, budget)}`;
  });

  // Earlier turns, so a follow-up like "po pse?" is read as part of a
  // conversation rather than as a question about nothing.
  const past = history.length
    ? `BISEDA DERI TANI:\n${history
        .map((t) => `Lexuesi: ${t.question}\n383: ${t.answer}`)
        .join("\n\n")}\n\n`
    : "";

  return `${past}PYETJA E LEXUESIT:\n${question}\n\nARTIKUJT E BOTUAR TE 383:\n\n${blocks.join("\n\n---\n\n")}`;
}

/**
 * Decide whether what came back may be shown.
 *
 * Returns either a grounded answer with the citations resolved to real
 * sources, or a refusal. There is no third outcome, and no path that shows
 * model text without at least one valid citation behind it.
 */
export function validateAnswer(raw, sourceCount) {
  if (!raw || typeof raw !== "object") return { grounded: false, reason: "no-json" };
  if (raw.enough === false) return { grounded: false, reason: "model-declined" };

  const answer = typeof raw.answer === "string" ? raw.answer.trim() : "";
  if (answer.length < 12) return { grounded: false, reason: "empty-answer" };
  // A model that ignores "2–4 fjali" this badly has stopped following the
  // prompt, and the citation check is not worth trusting on the same output.
  if (answer.length > 1600) return { grounded: false, reason: "runaway-answer" };

  const cited = Array.isArray(raw.sources) ? raw.sources : [];
  const valid = [];
  for (const value of cited) {
    const n = typeof value === "number" ? value : Number.parseInt(String(value), 10);
    if (!Number.isInteger(n) || n < 1 || n > sourceCount) continue;
    if (!valid.includes(n)) valid.push(n);
  }

  // The gate. No verifiable source, no answer — however plausible it reads.
  if (valid.length === 0) return { grounded: false, reason: "no-valid-citation" };

  return { grounded: true, answer, sources: valid };
}
