"use client";

type HistoryPoint = { createdAt: string; probabilities: Record<string, number>; lap?: number; status?: string };
type Driver = { key: string; label: string; team: string; probability: number };
const TEAM: Record<string, string> = { McLaren: "#ff8000", Ferrari: "#e8002d", Mercedes: "#27f4d2", "Red Bull": "#3671c6", Williams: "#64c4ff", AstonMartin: "#229971", Audi: "#b8b8b8", Alpine: "#ff87bc", Haas: "#b6babd", Cadillac: "#d7aa33" };
const color = (team: string) => TEAM[team?.replace(" F1 Team", "")] ?? "#7a6754";

export default function F1ProbabilityHistory({ drivers, history }: { drivers: Driver[]; history: HistoryPoint[] }) {
  if (history.length < 2) return <div className="mb-5 rounded-2xl border border-[#ddcfbd] bg-[#fffaf1] p-4 text-sm text-[#695b4b]">Nuk u ruajtën vektorë live për këtë garë. Historia e gjasave nuk mund të rikrijohet pa të dhëna të verifikuara.</div>;
  const last = Math.max(history.length - 1, 1);
  const laps = history.map((point) => Number(point.lap ?? 0));
  const lapLabel = laps.some(Boolean) ? `Lap ${Math.min(...laps.filter(Boolean))}–${Math.max(...laps)}` : `${history.length} vektorë të ruajtur`;
  return <section className="mb-5 rounded-2xl border border-[#ddcfbd] bg-[#fffaf1] p-4 text-[#211b16] shadow-[0_12px_30px_rgba(75,46,20,.08)]"><div className="mb-3 flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs font-bold tracking-[.16em] text-orange-600">PROBABILITET E VERIFIKUARA</p><h3 className="mt-1 font-black">Historia lap-pas-lapi</h3></div><span className="font-mono text-[11px] text-[#806d58]">{lapLabel}</span></div><div className="h-72 overflow-hidden rounded-xl border border-[#eadfce] bg-[#fffdf8] p-3"><svg viewBox="0 0 1000 300" preserveAspectRatio="none" className="h-full w-full" role="img" aria-label="Grafiku lap pas lapi i gjasave të 22 pilotëve"><g stroke="#e9decd" strokeWidth="1"><line x1="0" x2="1000" y1="50" y2="50"/><line x1="0" x2="1000" y1="150" y2="150"/><line x1="0" x2="1000" y1="250" y2="250"/></g>{drivers.map((driver) => <polyline key={driver.key} points={history.map((point,index) => `${index / last * 1000},${290 - Math.max(0, Math.min(1, Number(point.probabilities[driver.key] ?? 0))) * 270}`).join(" ")} fill="none" stroke={color(driver.team)} strokeWidth="2.5" strokeOpacity=".92" vectorEffect="non-scaling-stroke" />)}</svg></div><div className="mt-3 grid grid-cols-2 gap-x-3 gap-y-1 sm:grid-cols-4 lg:grid-cols-6">{drivers.map((driver) => <span key={driver.key} className="flex items-center gap-1.5 font-mono text-[10px] text-[#635343]"><i className="h-2 w-2 rounded-full" style={{backgroundColor:color(driver.team)}}/>{driver.key}</span>)}</div><p className="mt-3 text-xs text-[#806d58]">Çdo pikë është një vektor i ruajtur nga Formula 1 Dashboard; mungesat nuk interpolohen.</p></section>;
}
