"use client";
import { useMemo, useState } from "react";
type Driver={key:string;label:string;team:string;probability:number;headshot_url?:string;grid_position?:number};
type TimingRow={driver_code?:string;position?:number;gap?:string;pits?:number;status?:string};
const teamColor:Record<string,string>={McLaren:"#ff8000",Ferrari:"#e8002d",Mercedes:"#27f4d2","Red Bull":"#3671c6",Williams:"#64c4ff",AstonMartin:"#229971",Audi:"#b8b8b8",Alpine:"#ff87bc",Haas:"#b6babd",Cadillac:"#d7aa33"};
export default function F1RaceControl({drivers,timing}:{drivers:Driver[];timing:{race?:{status?:string;current_lap?:number;total_laps?:number};rows?:TimingRow[]}|null}){
 const [gapMode,setGapMode]=useState<"ahead"|"leader">("ahead"); const [expanded,setExpanded]=useState(false); const ranked=useMemo(()=>[...drivers].sort((a,b)=>b.probability-a.probability),[drivers]); const live=timing?.race?.status==="LIVE"; const rows=timing?.rows??[];
 return <section className="rounded-2xl border border-white/10 bg-[#101114] p-4 text-white shadow-2xl shadow-black/30 md:p-6">
  <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold tracking-[.18em] text-orange-400">F1 RACE CONTROL</p><h2 className="mt-1 text-2xl font-black tracking-tight">22 pilotë, një fitues</h2></div><div className="font-mono text-xs text-zinc-400">{live?`LIVE · LAP ${timing?.race?.current_lap??"?"}/${timing?.race?.total_laps??"?"}`:"GRID PENDING"}</div></div>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><div><div className="mb-3 flex items-center justify-between"><h3 className="font-bold">Top 10 sipas gjasës</h3><span className="text-xs text-zinc-500">Përditësohet nga koha zyrtare</span></div><div className="relative h-64 overflow-hidden rounded-xl border border-white/10 bg-[#15171b] p-4"><div className="absolute inset-x-4 top-1/2 border-t border-dashed border-white/10"/><div className="absolute inset-y-4 left-1/2 border-l border-dashed border-white/10"/><div className="flex h-full items-end gap-2">{ranked.slice(0,10).map((d,i)=><div key={d.key} className="group flex h-full min-w-0 flex-1 flex-col justify-end" title={`${d.label}: ${(d.probability*100).toFixed(1)}%`}><div className="transition-all duration-500" style={{height:`${Math.max(4,d.probability*100)}%`,background:teamColor[d.team?.replace(" F1 Team","")]??"#f97316"}}/><span className="mt-2 truncate text-center font-mono text-[10px] text-zinc-300">{d.key}</span></div>)}</div></div>
  <div className="mt-5"><div className="mb-2 flex items-center justify-between"><h3 className="font-bold">Renditja live</h3><div className="rounded-lg border border-white/10 p-1 text-xs"><button onClick={()=>setGapMode("ahead")} className={gapMode==="ahead"?"rounded bg-orange-500 px-2 py-1 text-black":"px-2 py-1 text-zinc-400"}>Para</button><button onClick={()=>setGapMode("leader")} className={gapMode==="leader"?"rounded bg-orange-500 px-2 py-1 text-black":"px-2 py-1 text-zinc-400"}>Lideri</button></div></div><div className="max-h-[420px] overflow-y-auto rounded-xl border border-white/10">{ranked.slice(0, expanded ? 22 : 10).map((d,i)=>{const r=rows.find(x=>x.driver_code===d.key);return <div key={d.key} className="grid grid-cols-[32px_1fr_auto_auto] items-center gap-3 border-b border-white/5 px-3 py-3 last:border-0"><span className="font-mono text-zinc-500">{r?.position??i+1}</span><span><b>{d.label}</b><small className="ml-2 text-zinc-500">{d.team}</small></span><span className="font-mono text-xs text-zinc-400">{r?.status??(gapMode==="leader"?r?.gap??"-":"-")}</span><span className="font-mono font-bold" style={{color:teamColor[d.team?.replace(" F1 Team","")]??"#f97316"}}>{(d.probability*100).toFixed(1)}%</span></div>})}</div>{ranked.length > 10 && <button type="button" onClick={()=>setExpanded(!expanded)} className="mt-3 w-full rounded-lg border border-orange-400/40 px-3 py-2 text-sm font-bold text-orange-300">{expanded ? "Mbyll listën" : "Vazhdo më shumë"}</button>}</div></div>
  <aside className="rounded-xl border border-orange-400/30 bg-gradient-to-b from-orange-500/10 to-transparent p-4"><h3 className="font-bold">{live?"Pozicionet zyrtare":"Gridi i nisjes"}</h3><p className="mt-1 text-xs text-zinc-400">{live?"Pozicion, interval dhe pit stop nga Formula 1 Dashboard.":"Slotet e nisjes shfaqen kur gridi zyrtar verifikohet."}</p><div className="mt-4 grid grid-cols-2 gap-2">{[...drivers].sort((a,b)=>(a.grid_position??99)-(b.grid_position??99)).map((d,i)=><div key={d.key} className="rounded border border-orange-400/30 bg-[#171717] p-2 transition-transform duration-300 hover:-translate-y-0.5" style={{animation:`pulse 2.8s ease-in-out ${i*110}ms infinite`}}><span className="font-mono text-[10px] text-orange-300">P{d.grid_position??i+1}</span>{d.headshot_url?<img src={d.headshot_url} alt={d.label} className="mt-2 h-9 w-9 rounded-full border border-orange-400/40 object-cover"/>:<div className="mt-2 flex h-9 w-9 items-center justify-center rounded-full bg-orange-500/15 text-xs font-black text-orange-200">{d.key}</div>}<b className="mt-1 block truncate text-xs">{d.label}</b></div>)}</div></aside></div></section>
}