/**
 * Generates the seed migration for the dossier from the hand-written data that
 * is currently in lib/topics.mjs.
 *
 * Everything lands as `status = 'draft'`. None of it is grandfathered to
 * approved, and that is the point: this is exactly the unsourced text the new
 * schema exists to replace, and approving it at seed time would launder the
 * problem into the new tables on day one. Two of the forty-two carry a source
 * string; the rest have never been checked against anything.
 *
 * The visible consequence is that the dossier renders empty until the queue is
 * drained by hand. That is the honest price of "omit rather than approximate".
 *
 *   node scripts/dosje_seed.mjs > supabase/migrations/0052_dosje_seed.sql
 */

import { TOPICS } from "../lib/topics.mjs";

/** Postgres string literal. */
const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);

/** Postgres text[] literal. */
const arr = (xs) =>
  xs && xs.length ? `array[${xs.map((x) => q(x)).join(", ")}]::text[]` : `'{}'::text[]`;

const MONTHS = {
  janar: 1, shkurt: 2, mars: 3, prill: 4, maj: 5, qershor: 6,
  korrik: 7, gusht: 8, shtator: 9, tetor: 10, nentor: 11, dhjetor: 12,
};

const fold = (s) =>
  String(s ?? "").toLowerCase().replaceAll("ë", "e").replaceAll("ç", "c");

/**
 * A sortable date plus how precise it honestly is. "19 prill 2013" is a day,
 * "Qershor 1999" is a month, "2013" is a year, and "Çdo vit" is none of them —
 * those cannot be placed on a timeline and are reported rather than guessed.
 */
function parseDate(m) {
  const raw = fold(m.date ?? "");
  const year = (raw.match(/\b(19|20)\d{2}\b/) || [])[0] ?? null;
  if (!year) return null;

  const month = Object.keys(MONTHS).find((name) => raw.includes(name));
  const day = (raw.match(/^\s*(\d{1,2})\b/) || [])[1] ?? null;

  if (month && day) {
    return { date: `${year}-${String(MONTHS[month]).padStart(2, "0")}-${String(day).padStart(2, "0")}`, precision: "day" };
  }
  if (month) {
    return { date: `${year}-${String(MONTHS[month]).padStart(2, "0")}-01`, precision: "month" };
  }
  return { date: `${year}-01-01`, precision: "year" };
}

const dedupe = (m) =>
  `${fold(m.title).replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`.slice(0, 120);

const out = [];
const skipped = [];

out.push(`-- 0052 — Dosje seed: the existing timeline, as drafts.
--
-- Generated by scripts/dosje_seed.mjs from lib/topics.mjs. Do not hand-edit;
-- regenerate.
--
-- Every milestone enters as 'draft' and none is publicly readable. Two of them
-- carry a source string in the old data and it is preserved as a citation with
-- no http_status, which deliberately does not count toward the two-publisher
-- minimum until it has actually been fetched.
--
-- Applying this migration renders the dossier empty. That is expected.
`);

for (const t of TOPICS) {
  // Anchors and excludes are seeded conservatively: the topic's own name is an
  // anchor, and the generic terms that caused false matches become signals.
  const generic = new Set(["nato", "shba", "uashington", "bruksel", "brukselit", "ambasada", "kandidat", "liberalizim", "be-ja", "be-se"]);
  const anchors = t.forms.filter((f) => !generic.has(fold(f)));
  const signals = t.forms.filter((f) => generic.has(fold(f)));

  out.push(`
insert into public.dosje_topics (slug, title, blurb, status, anchors, signals, excludes)
values (${q(t.slug)}, ${q(t.title)}, ${q(t.blurb)}, 'draft', ${arr(anchors)}, ${arr(signals)}, '{}'::text[])
on conflict (slug) do nothing;`);

  for (const m of t.milestones) {
    const d = parseDate(m);
    if (!d) {
      skipped.push(`${t.slug}: ${m.title} (date "${m.date}")`);
      continue;
    }
    out.push(`
insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values (${q(t.slug)}, date ${q(d.date)}, ${q(d.precision)}, ${q(m.date)}, ${q(m.tag)},
        ${q(m.title)}, ${q(m.summary)}, ${q(m.why)}, 'draft', 'hand-written (pre-pipeline)', ${q(dedupe(m))})
on conflict (topic_slug, dedupe_key) do nothing;`);

    if (m.source) {
      out.push(`
-- Recorded as provenance, not as a verified citation: no url, no fetch, so it
-- cannot satisfy the two-publisher rule.
insert into public.dosje_citations (milestone_id, url, publisher, source_title)
select id, 'https://example.invalid/unverified', ${q(m.source)}, ${q("burim i deklaruar, i paverifikuar")}
  from public.dosje_milestones
 where topic_slug = ${q(t.slug)} and dedupe_key = ${q(dedupe(m))}
on conflict (milestone_id, url) do nothing;`);
    }
  }
}

if (skipped.length) {
  out.push(`
-- Not seeded — these carry no placeable date and need one before they can be
-- reviewed:
${skipped.map((s) => `--   ${s}`).join("\n")}`);
}

process.stdout.write(out.join("\n") + "\n");
process.stderr.write(
  `seeded ${TOPICS.length} topics, ` +
    `${TOPICS.reduce((n, t) => n + t.milestones.length, 0) - skipped.length} milestones as draft` +
    (skipped.length ? `, skipped ${skipped.length} with unplaceable dates\n` : "\n")
);
