/**
 * Kosova në xhep help layer: curated, sourced travel facts in EN and SQ, and
 * the pure logic that picks what applies to one visitor. Every item carries
 * a source and the date it was checked; the UI shows both and flags prices
 * older than PRICE_STALE_DAYS. Nothing here is generated by AI.
 *
 * Research pass: 2026-10-03 (sources read in full, quoted where possible).
 */

export const CHECKED_AT = "2026-10-03";
export const PRICE_STALE_DAYS = 120;

const SRC = {
  fcdoEntry: { name: "UK FCDO travel advice — Kosovo entry requirements", url: "https://www.gov.uk/foreign-travel-advice/kosovo/entry-requirements" },
  fcdoSafety: { name: "UK FCDO travel advice — Kosovo safety and security", url: "https://www.gov.uk/foreign-travel-advice/kosovo/safety-and-security" },
  kib: { name: "Kosovo Insurance Bureau via AMRKS — border insurance", url: "https://amrks.org/en/border-insurance/" },
  rac: { name: "RAC — Driving in Kosovo", url: "https://www.rac.co.uk/drive/travel/country/kosovo/" },
  airportBus: { name: "Transport in Pristina (line 1A)", url: "https://en.wikipedia.org/wiki/Transport_in_Pristina" },
  airportGuide: { name: "The Balkan Guide — Pristina airport transfer", url: "https://www.thebalkanguide.com/practical/pristina-airport-transfer/" },
  sim: { name: "Kosovo SIM cards 2026: Vala and IPKO", url: "https://megaesim.com/blog/kosovo-sim-card-airport-guide/" },
  bqk: { name: "Central Bank of Kosovo — currency in circulation", url: "https://bqk-kos.org/operacionet-bankare/paraja-ne-qarkullim/?lang=en" },
  numbeo: { name: "Numbeo — cost of living in Pristina (updated 30 Sep 2026)", url: "https://www.numbeo.com/cost-of-living/in/Pristina" },
  brezovicaPrices: { name: "Brezovica Ski Resort — prices 2025–26", url: "https://www.brezovica-ski.net/prices" },
  brezovicaSeason: { name: "Skiresort.info — Brezovica", url: "https://www.skiresort.info/ski-resort/brezovica/" },
  holidays: { name: "Swiss FDFA — public holidays in Kosovo", url: "https://www.eda.admin.ch/countries/kosovo/en/home/news/official-holidays.html" },
  flagDay: { name: "Public holidays in Kosovo", url: "https://en.wikipedia.org/wiki/Public_holidays_in_Kosovo" },
};

/* --------------------------------------------------------------- route */

export const ROUTE_PLACES = ["fly", "albania", "north-macedonia", "montenegro", "serbia"];

const ROUTE_RULES = {
  serbiaExit: {
    level: "stop",
    title: { en: "Leaving for Serbia? Check your entry stamp first", sq: "Po del drejt Serbisë? Kontrollo vulën e hyrjes" },
    body: {
      en: "The UK government warns you cannot travel from Kosovo into Serbia unless you entered Serbia first (a Serbian stamp from a Serbian airport or border). Serbian border guards have refused entry to foreigners with Kosovo stamps. If you came in from Albania, North Macedonia, Montenegro or by air, plan to leave through a different country.",
      sq: "Qeveria britanike paralajmëron se nuk mund të kalosh nga Kosova në Serbi nëse nuk ke hyrë më parë në Serbi (vulë serbe nga aeroporti ose kufiri serb). Rojet serbe kanë refuzuar hyrjen e të huajve me vula të Kosovës. Nëse ke hyrë nga Shqipëria, Maqedonia e Veriut, Mali i Zi ose me aeroplan, planifiko daljen përmes një vendi tjetër.",
    },
    source: SRC.fcdoEntry,
  },
  insurance: {
    level: "must",
    title: { en: "Buy border insurance for your car", sq: "Bli sigurimin kufitar për makinën" },
    body: {
      en: "The European Green Card is not valid in Kosovo. Cars with foreign plates buy third-party border insurance from the Kosovo Insurance Bureau at the crossing — around €15 for 15 days for a car. Green Cards from Albania and North Macedonia are recognised, so those plates are exempt.",
      sq: "Karta e Gjelbër evropiane nuk vlen në Kosovë. Makinat me targa të huaja blejnë sigurimin kufitar për palë të treta nga Byroja Kosovare e Sigurimeve në pikën kufitare — rreth 15 € për 15 ditë për veturë. Kartat e Gjelbra të Shqipërisë dhe Maqedonisë së Veriut njihen, prandaj ato targa përjashtohen.",
    },
    source: SRC.kib,
    extraSource: SRC.rac,
  },
  drivingRules: {
    level: "know",
    title: { en: "Rules of the road", sq: "Rregullat e rrugës" },
    body: {
      en: "Zero tolerance on drink-driving (the limit is 0.01%). A warning triangle is compulsory. Limits: 50 km/h in towns, 80 km/h outside, 130 km/h on the motorway. Roads range from fair to poor, worst in rural areas and after bad weather.",
      sq: "Tolerancë zero për alkoolin në timon (kufiri 0,01%). Trekëndëshi i paralajmërimit është i detyrueshëm. Kufijtë: 50 km/h në qytet, 80 km/h jashtë, 130 km/h në autostradë. Rrugët variojnë nga të mira në të dobëta, më keq në zona rurale dhe pas motit të keq.",
    },
    source: SRC.rac,
    extraSource: SRC.fcdoSafety,
  },
  passport: {
    level: "know",
    title: { en: "Passport and stay", sq: "Pasaporta dhe qëndrimi" },
    body: {
      en: "UK visitors can stay up to 90 days without a visa for business or tourism. Rules depend on your nationality — check yours before you go.",
      sq: "Vizitorët nga Mbretëria e Bashkuar mund të qëndrojnë deri në 90 ditë pa vizë për biznes ose turizëm. Rregullat varen nga shtetësia — kontrolloje tëndën para nisjes.",
    },
    source: SRC.fcdoEntry,
  },
};

/**
 * The rules that apply to a route. `entry`/`exit` are ROUTE_PLACES; a car is
 * assumed whenever the entry is a land border.
 */
export function routeWarnings({ entry, exit }) {
  const from = ROUTE_PLACES.includes(entry) ? entry : "fly";
  const to = ROUTE_PLACES.includes(exit) ? exit : from;
  const ids = [];
  if (to === "serbia" && from !== "serbia") ids.push("serbiaExit");
  if (from !== "fly") ids.push("insurance", "drivingRules");
  ids.push("passport");
  return ids.map((id) => ({ id, ...ROUTE_RULES[id] }));
}

/** Map a quiz crossing to the country on the other side. */
export function entryFromCrossing(crossing, arrival) {
  if (arrival !== "drive") return "fly";
  return { kulle: "montenegro", merdare: "serbia", "hani-i-elezit": "north-macedonia", "vermice-morine": "albania" }[crossing] ?? "albania";
}

/* ------------------------------------------------------------- arrival */

const ARRIVAL = {
  fly: [
    {
      id: "bus",
      title: { en: "Airport bus 1A to the centre", sq: "Autobusi 1A nga aeroporti në qendër" },
      body: {
        en: "Line 1A runs about hourly from 04:00 to 21:00 and takes 30–40 minutes to the bus station and centre. Tickets cost around €3.",
        sq: "Linja 1A qarkullon afërsisht çdo orë nga 04:00 deri në 21:00 dhe zgjat 30–40 minuta deri te stacioni i autobusëve dhe qendra. Bileta kushton rreth 3 €.",
      },
      source: SRC.airportBus,
      extraSource: SRC.airportGuide,
    },
    {
      id: "taxi",
      title: { en: "Taxi to Prishtina", sq: "Taksi për në Prishtinë" },
      body: {
        en: "Expect roughly €15–25 to the centre, 20–25 minutes in normal traffic. Registered taxi firms are the safest choice and fares are regulated; agree the price or check the meter before you set off.",
        sq: "Llogarit rreth 15–25 € deri në qendër, 20–25 minuta në trafik normal. Kompanitë e regjistruara të taksive janë zgjedhja më e sigurt dhe tarifat janë të rregulluara; merruni vesh për çmimin ose kontrollo taksimetrin para nisjes.",
      },
      source: SRC.airportGuide,
      extraSource: SRC.fcdoSafety,
    },
  ],
  drive: [
    {
      id: "insuranceDesk",
      title: { en: "First stop: the insurance desk", sq: "Ndalesa e parë: sporteli i sigurimit" },
      body: {
        en: "Unless your car has Albanian or North Macedonian plates, buy the border insurance at the crossing before driving on (around €15 for 15 days).",
        sq: "Nëse makina nuk ka targa të Shqipërisë ose Maqedonisë së Veriut, bli sigurimin kufitar në pikë para se të vazhdosh (rreth 15 € për 15 ditë).",
      },
      source: SRC.kib,
      extraSource: SRC.rac,
    },
    {
      id: "documents",
      title: { en: "Keep these in the car", sq: "Mbaji këto në makinë" },
      body: {
        en: "Driving licence, registration document, your insurance certificate and a warning triangle. Drivers from the UK also need headlamp converters unless the lights adjust.",
        sq: "Patentën, dokumentin e regjistrimit, certifikatën e sigurimit dhe trekëndëshin e paralajmërimit. Shoferët nga Mbretëria e Bashkuar duhet të kenë edhe ngjitëse për dritat, nëse ato nuk rregullohen.",
      },
      source: SRC.rac,
    },
  ],
  both: [
    {
      id: "sim",
      title: { en: "Mobile data", sq: "Interneti celular" },
      body: {
        en: "The two networks are Vala and IPKO. IPKO sells SIM cards at the airport; both have shops in every town. Tourist packs start at a few euros — prices vary, so compare in the shop.",
        sq: "Dy rrjetet janë Vala dhe IPKO. IPKO shet karta SIM në aeroport; të dyja kanë dyqane në çdo qytet. Paketat turistike nisin nga disa euro — çmimet ndryshojnë, krahasoji në dyqan.",
      },
      source: SRC.sim,
    },
    {
      id: "money",
      title: { en: "Money", sq: "Paratë" },
      body: {
        en: "Kosovo uses the euro. Carry some cash for small cafés, bakeries and markets.",
        sq: "Kosova përdor euron. Mbaj pak para në dorë për kafene të vogla, furra dhe tregje.",
      },
      source: SRC.bqk,
    },
  ],
};

export function arrivalItems(arrival) {
  return [...(arrival === "drive" ? ARRIVAL.drive : ARRIVAL.fly), ...ARRIVAL.both];
}

/* -------------------------------------------------------------- prices */

export const PRICES = [
  { id: "cappuccino", label: { en: "Cappuccino", sq: "Kapuçino" }, eur: 1.68, source: SRC.numbeo },
  { id: "cheapMeal", label: { en: "Meal, inexpensive restaurant", sq: "Vakt në restorant të lirë" }, eur: 5, source: SRC.numbeo },
  { id: "dinnerForTwo", label: { en: "Dinner for two, mid-range", sq: "Darkë për dy, restorant mesatar" }, eur: 30, source: SRC.numbeo },
  { id: "beer", label: { en: "Local draught beer (0.5 L)", sq: "Birrë vendore (0,5 L)" }, eur: 2.5, source: SRC.numbeo },
  { id: "water", label: { en: "Bottled water (0.33 L)", sq: "Ujë në shishe (0,33 L)" }, eur: 0.94, source: SRC.numbeo },
  { id: "cityBus", label: { en: "City bus ticket", sq: "Biletë autobusi urban" }, eur: 0.5, source: SRC.numbeo },
  { id: "taxiStart", label: { en: "Taxi start + per km", sq: "Nisja e taksisë + për km" }, eur: 2, perKm: 0.5, source: SRC.numbeo },
  { id: "petrol", label: { en: "Petrol, per litre", sq: "Benzinë, për litër" }, eur: 1.31, source: SRC.numbeo },
  { id: "skiPass", label: { en: "Brezovica day ski pass", sq: "Biletë ditore ski në Brezovicë" }, eur: 22, source: SRC.brezovicaPrices, interest: "skiing" },
];

export function pricesAreStale(now = new Date(), checkedAt = CHECKED_AT) {
  return (now.getTime() - Date.parse(checkedAt)) / 86_400_000 > PRICE_STALE_DAYS;
}

/* -------------------------------------------------------------- events */

/** Month/day ranges (inclusive). A range may wrap the year (Dec → Mar). */
export const EVENTS = [
  {
    id: "flagDay",
    from: [11, 28],
    to: [11, 28],
    title: { en: "Albanian Flag Day", sq: "Dita e Flamurit" },
    body: { en: "Widely celebrated across Kosovo with flags, music and gatherings.", sq: "Festohet gjerësisht në Kosovë me flamuj, muzikë dhe tubime." },
    source: SRC.flagDay,
  },
  {
    id: "skiSeason",
    from: [12, 1],
    to: [3, 31],
    title: { en: "Ski season at Brezovica", sq: "Sezoni i skijimit në Brezovicë" },
    body: { en: "Kosovo's main ski resort in the Sharr Mountains usually runs from December to March, snow permitting. Day passes are around €22.", sq: "Qendra kryesore e skijimit në Malet e Sharrit zakonisht punon nga dhjetori deri në mars, nëse ka borë. Bileta ditore rreth 22 €." },
    source: SRC.brezovicaSeason,
    extraSource: SRC.brezovicaPrices,
    interest: "skiing",
  },
  {
    id: "christmasCatholic",
    from: [12, 25],
    to: [12, 25],
    title: { en: "Catholic Christmas (public holiday)", sq: "Krishtlindjet katolike (festë zyrtare)" },
    body: { en: "Public holiday; some shops and offices close.", sq: "Festë zyrtare; disa dyqane dhe zyra mbyllen." },
    source: SRC.holidays,
  },
  {
    id: "newYear",
    from: [12, 31],
    to: [1, 2],
    title: { en: "New Year (public holiday 1–2 January)", sq: "Viti i Ri (festë zyrtare 1–2 janar)" },
    body: { en: "Celebrations on New Year's Eve; 1 and 2 January are public holidays.", sq: "Festime natën e Vitit të Ri; 1 dhe 2 janari janë festa zyrtare." },
    source: SRC.holidays,
  },
  {
    id: "christmasOrthodox",
    from: [1, 7],
    to: [1, 7],
    title: { en: "Orthodox Christmas (public holiday)", sq: "Krishtlindjet ortodokse (festë zyrtare)" },
    body: { en: "Public holiday.", sq: "Festë zyrtare." },
    source: SRC.holidays,
  },
  {
    id: "independenceDay",
    from: [2, 17],
    to: [2, 17],
    title: { en: "Independence Day", sq: "Dita e Pavarësisë" },
    body: { en: "Kosovo's biggest celebration, marking the 2008 declaration of independence; expect crowds and events in Prishtina.", sq: "Festa më e madhe e Kosovës, në përvjetor të shpalljes së pavarësisë më 2008; prit turma dhe aktivitete në Prishtinë." },
    source: SRC.holidays,
  },
];

const dayOfYear = (month, day) => Date.UTC(2001, month - 1, day) / 86_400_000;

function inRange(month, day, from, to) {
  const d = dayOfYear(month, day);
  const a = dayOfYear(from[0], from[1]);
  const b = dayOfYear(to[0], to[1]);
  return a <= b ? d >= a && d <= b : d >= a || d <= b;
}

/**
 * Events overlapping the visitor's stay. With a start date, the exact days;
 * with only a month, the whole month. Nothing known → [].
 */
export function eventsFor({ startDate, month, days }) {
  const stay = [];
  if (typeof startDate === "string" && /^\d{4}-\d{2}-\d{2}$/.test(startDate)) {
    const start = Date.parse(`${startDate}T00:00:00Z`);
    const n = Math.min(60, Math.max(1, Number(days) || 1));
    for (let i = 0; i < n; i += 1) {
      const d = new Date(start + i * 86_400_000);
      stay.push([d.getUTCMonth() + 1, d.getUTCDate()]);
    }
  } else if (Number.isInteger(month) && month >= 1 && month <= 12) {
    const len = new Date(Date.UTC(2001, month, 0)).getUTCDate();
    for (let day = 1; day <= len; day += 1) stay.push([month, day]);
  } else {
    return [];
  }
  return EVENTS.filter((event) => stay.some(([m, d]) => inRange(m, d, event.from, event.to)));
}

/* ------------------------------------------------------------- phrases */

/** Show-to-a-local phrases. Albanian is the big line; English is the subtitle. */
export const PHRASES = [
  { id: "address", sq: "Më çoni te kjo adresë, ju lutem.", en: "Please take me to this address." },
  { id: "howMuch", sq: "Sa kushton?", en: "How much is it?" },
  { id: "bill", sq: "Llogarinë, ju lutem.", en: "The bill, please." },
  { id: "macchiato", sq: "Një makiato, ju lutem.", en: "A macchiato, please." },
  { id: "noMeat", sq: "Nuk ha mish.", en: "I don't eat meat." },
  { id: "noPork", sq: "Pa mish derri, ju lutem.", en: "No pork, please." },
  { id: "nutAllergy", sq: "Kam alergji nga arrat.", en: "I'm allergic to nuts." },
  { id: "pharmacy", sq: "Ku është barnatorja më e afërt?", en: "Where is the nearest pharmacy?" },
  { id: "doctor", sq: "Më duhet një mjek.", en: "I need a doctor." },
  { id: "ambulance", sq: "Thirrni ambulancën, ju lutem!", en: "Please call an ambulance!" },
  { id: "toilet", sq: "Ku është tualeti?", en: "Where is the toilet?" },
  { id: "english", sq: "A flisni anglisht?", en: "Do you speak English?" },
  { id: "slowly", sq: "Ju lutem, flisni ngadalë.", en: "Please speak slowly." },
  { id: "thanks", sq: "Faleminderit shumë!", en: "Thank you very much!" },
];
