/**
 * Kosova në xhep help layer: curated, sourced travel facts in EN and SQ, and
 * the pure logic that picks what applies to one visitor. Every item carries
 * a source and the date it was checked; the UI shows both and flags prices
 * older than PRICE_STALE_DAYS. Nothing here is generated by AI.
 *
 * Research passes: 2026-10-03, re-checked line by line 2026-10-04 against the
 * official sources (operator timetables, FCDO, RAC, KIB); corrected the airport
 * bus (every 2 h, €6/€5), city bus fare (€0.80), SIM (Vala at the airport,
 * passport needed), border insurance (+ one month), holidays, and safety.
 */

export const CHECKED_AT = "2026-10-04";
export const PRICE_STALE_DAYS = 120;

const SRC = {
  fcdoEntry: { name: "UK FCDO travel advice — Kosovo entry requirements", url: "https://www.gov.uk/foreign-travel-advice/kosovo/entry-requirements" },
  fcdoSafety: { name: "UK FCDO travel advice — Kosovo safety and security", url: "https://www.gov.uk/foreign-travel-advice/kosovo/safety-and-security" },
  kib: { name: "Kosovo Insurance Bureau via AMRKS — border insurance", url: "https://amrks.org/en/border-insurance/" },
  rac: { name: "RAC — Driving in Kosovo", url: "https://www.rac.co.uk/drive/travel/country/kosovo/" },
  airportBus: { name: "Trafiku Urban — airport line 1A timetable and fares (July 2026)", url: "https://trafikurban-pr.com/2022/linja-e-aeroportit/" },
  cityBus: { name: "Trafiku Urban — ticket prices", url: "https://trafikurban-pr.com/2022/orari-dhe-linjat/" },
  airportGuide: { name: "The Balkan Guide — Pristina airport transfer", url: "https://www.thebalkanguide.com/practical/pristina-airport-transfer/" },
  sim: { name: "esim.net — buying a prepaid SIM in Kosovo (2026)", url: "https://www.esim.net/guides/kosovo-sim-card-guide/" },
  insurancePrice: { name: "Telegrafi — border insurance for diaspora cars", url: "https://telegrafi.com/en/compatriots-continue-to-pay-border-insurance-for-cars/" },
  fuel: { name: "383ks.com daily fuel prices (NaftaSot)", url: "https://naftasot.com/" },
  bqk: { name: "Central Bank of Kosovo — currency in circulation", url: "https://bqk-kos.org/operacionet-bankare/paraja-ne-qarkullim/?lang=en" },
  numbeo: { name: "Numbeo — cost of living in Pristina (updated 30 Sep 2026)", url: "https://www.numbeo.com/cost-of-living/in/Pristina" },
  brezovicaPrices: { name: "Brezovica Ski Resort — prices 2025–26", url: "https://www.brezovica-ski.net/prices" },
  brezovicaSeason: { name: "Skiresort.info — Brezovica", url: "https://www.skiresort.info/ski-resort/brezovica/" },
  holidays: { name: "Swiss FDFA — public holidays in Kosovo", url: "https://www.eda.admin.ch/countries/kosovo/en/home/news/official-holidays.html" },
  flagDay: { name: "Public holidays in Kosovo", url: "https://en.wikipedia.org/wiki/Public_holidays_in_Kosovo" },
  ame: { name: "Emergency Management Agency of Kosovo — numbers for the public", url: "https://ame.rks-gov.net/post/en-us/88/communication-for-the-public" },
  trafficLaw: { name: "Kosovo Police — offences under the Law on Road Traffic Rules (06-L-069)", url: "https://www.kosovopolice.com/wp-content/uploads/2019/10/P%C3%8BRSHKRIMI_I_KUND%C3%8BRVAJTJEVE_DHE_MASAVE_ND%C3%8BSHKUESE_NGA_Ligji_nr._06-L-069_p%C3%ABr_ndryshimin_dhe_plot%C3%ABsimin_e_Ligjit_nr._05-L-088_p%C3%ABr_rregullat_e_trafikut_rrugor.pdf" },
  winterGear: { name: "Kosovarja — winter equipment compulsory 15 Nov to 15 Mar", url: "https://www.kosovarja-ks.com/prej-sot-e-deri-ne-muajin-mars-gomat-e-dimrit-jane-te-obligueshme/" },
  plugs: { name: "Power Plugs & Sockets — Kosovo", url: "https://www.power-plugs-sockets.com/us/kosovo/" },
  phoneCode: { name: "Telephone numbers in Kosovo", url: "https://en.wikipedia.org/wiki/Telephone_numbers_in_Kosovo" },
  timeZone: { name: "timeanddate — time zone in Pristina", url: "https://www.timeanddate.com/time/zone/kosovo/pristina" },
  tipping: { name: "World Travel Guide — Kosovo food and drink", url: "https://www.worldtravelguide.net/guides/europe/kosovo/food-and-drink/" },
};

/* ----------------------------------------------------------- essentials */

/** The facts a visitor needs on day one, each with its source. `value` is the at-a-glance line. */
export const ESSENTIALS = [
  {
    id: "emergency",
    value: "112",
    title: { en: "Emergency numbers", sq: "Numrat e emergjencës" },
    body: {
      en: "112 for any emergency. Direct lines: 192 police, 193 fire and rescue, 194 ambulance. All are free and answer 24/7.",
      sq: "112 për çdo emergjencë. Linjat direkte: 192 policia, 193 zjarrfikësit dhe shpëtimi, 194 ambulanca. Të gjitha janë falas dhe përgjigjen 24/7.",
    },
    source: SRC.ame,
  },
  {
    id: "lights",
    value: { en: "Lights on", sq: "Dritat ndezur" },
    title: { en: "Headlights on, all day", sq: "Dritat ndezur, gjithë ditën" },
    body: {
      en: "Dipped headlights (or daytime running lights) must be on for the whole drive, day and night. Police stop and fine cars without them.",
      sq: "Dritat e shkurtra (ose dritat e ditës) duhet të jenë ndezur gjatë gjithë kohës së vozitjes, ditën e natën. Policia i ndal dhe i gjobit veturat pa to.",
    },
    source: SRC.trafficLaw,
  },
  {
    id: "winter",
    value: { en: "15 Nov–15 Mar", sq: "15 nën–15 mar" },
    title: { en: "Winter tyres", sq: "Gomat e dimrit" },
    body: {
      en: "From 15 November to 15 March, cars up to 3.5 t need winter tyres marked M+S on all four wheels, with at least 4 mm of tread, whatever the weather. Studded tyres are not allowed. The fine is €40.",
      sq: "Nga 15 nëntori deri më 15 mars, veturat deri në 3,5 t duhet të kenë goma dimri me shenjën M+S në të katër rrotat, me së paku 4 mm shara, pavarësisht motit. Gomat me thumba nuk lejohen. Gjoba është 40 €.",
    },
    source: SRC.trafficLaw,
    extraSource: SRC.winterGear,
  },
  {
    id: "cash",
    value: "€",
    title: { en: "Euro, cash and ATMs", sq: "Euro, para në dorë dhe bankomatë" },
    body: {
      en: "Prices are in euros. Cards work in cities, but cash is still used more, especially outside Prishtina. Use ATMs inside banks where you can, and keep cash in euros for the border insurance.",
      sq: "Çmimet janë në euro. Kartelat pranohen në qytete, por paratë në dorë përdoren ende më shumë, sidomos jashtë Prishtinës. Përdor bankomatët brenda bankave kur mundesh dhe mbaj euro në dorë për sigurimin kufitar.",
    },
    source: SRC.fcdoSafety,
    extraSource: SRC.bqk,
  },
  {
    id: "tipping",
    value: "~10%",
    title: { en: "Tipping", sq: "Bakshishi" },
    body: {
      en: "Not expected, always appreciated. Around 10% for good service in a restaurant if no service charge is on the bill; in a café people round up.",
      sq: "Nuk pritet, por gjithmonë mirëpritet. Rreth 10% për shërbim të mirë në restorant, nëse në faturë nuk është përfshirë shërbimi; në kafene njerëzit e rrumbullakojnë.",
    },
    source: SRC.tipping,
  },
  {
    id: "power",
    value: "230 V",
    title: { en: "Plugs", sq: "Prizat" },
    body: {
      en: "Type C and F sockets (the round two-pin European plug), 230 V, 50 Hz. UK and US visitors need an adapter.",
      sq: "Priza të tipit C dhe F (spina evropiane me dy kunja të rrumbullakëta), 230 V, 50 Hz. Vizitorët nga Britania dhe SHBA-ja kanë nevojë për përshtatës.",
    },
    source: SRC.plugs,
  },
  {
    id: "time",
    value: "UTC+1",
    title: { en: "Time zone", sq: "Zona kohore" },
    body: {
      en: "Central European Time, the same as Germany, Switzerland and Italy: UTC+1 in winter, UTC+2 in summer.",
      sq: "Ora e Evropës Qendrore, e njëjtë me Gjermaninë, Zvicrën dhe Italinë: UTC+1 në dimër, UTC+2 në verë.",
    },
    source: SRC.timeZone,
  },
  {
    id: "phone",
    value: "+383",
    title: { en: "Calling code", sq: "Prefiksi telefonik" },
    body: {
      en: "Kosovo's country code is +383. From a foreign SIM, dial local numbers with +383 in front and without the leading 0.",
      sq: "Prefiksi i Kosovës është +383. Nga një SIM e huaj, thirr numrat vendorë me +383 përpara dhe pa 0 në fillim.",
    },
    source: SRC.phoneCode,
  },
];

/* --------------------------------------------------------------- route */

export const ROUTE_PLACES = ["fly", "albania", "north-macedonia", "montenegro", "serbia"];

const ROUTE_RULES = {
  serbiaExit: {
    level: "stop",
    title: { en: "Leaving for Serbia? Check your entry stamp first", sq: "Po del drejt Serbisë? Kontrollo vulën e hyrjes" },
    body: {
      en: "Serbia does not treat its crossings with Kosovo as international borders. The UK government advises that to go from Kosovo into Serbia you need a Serbian entry stamp from earlier on the same trip (Belgrade, Niš or Kraljevo airport, or another Serbian border), and that people with Kosovo stamps have been refused. If you came in from Albania, North Macedonia, Montenegro or by air, leave through one of those instead.",
      sq: "Serbia nuk i trajton pikat e saj me Kosovën si kufij ndërkombëtarë. Qeveria britanike këshillon se për të kaluar nga Kosova në Serbi të duhet një vulë hyrjeje serbe nga i njëjti udhëtim (aeroporti i Beogradit, Nishit ose Kralevës, ose një kufi tjetër serb), dhe se personave me vula të Kosovës u është refuzuar hyrja. Nëse ke hyrë nga Shqipëria, Maqedonia e Veriut, Mali i Zi ose me aeroplan, dil nga një prej tyre.",
    },
    source: SRC.fcdoEntry,
  },
  insurance: {
    level: "must",
    title: { en: "Buy border insurance for your car", sq: "Bli sigurimin kufitar për makinën" },
    body: {
      en: "Kosovo is not in the Green Card system, so a European Green Card does not cover you here. Every car with foreign plates buys third-party border insurance from the Kosovo Insurance Bureau at the crossing: €15 for 15 days, €20 for a month. Only insurance from Albania and North Macedonia is recognised, so those plates are exempt.",
      sq: "Kosova nuk është pjesë e sistemit të Kartës së Gjelbër, ndaj Karta e Gjelbër evropiane nuk të mbulon këtu. Çdo veturë me targa të huaja blen sigurimin kufitar për palë të treta nga Byroja Kosovare e Sigurimit në pikën kufitare: 15 € për 15 ditë, 20 € për një muaj. Njihet vetëm sigurimi i Shqipërisë dhe i Maqedonisë së Veriut, ndaj ato targa përjashtohen.",
    },
    source: SRC.kib,
    extraSource: SRC.insurancePrice,
  },
  drivingRules: {
    level: "know",
    title: { en: "Rules of the road", sq: "Rregullat e rrugës" },
    body: {
      en: "Treat alcohol as zero: the RAC lists a 0.01% limit. Speed limits are 50 km/h in towns unless signed, 80 km/h outside towns and 130 km/h on the motorway. A warning triangle is compulsory; seat belts in every seat; under-12s may not sit in front. Roads range from fair to poor, worst in rural areas and after bad weather, with a risk of landslides and flooding, so avoid driving at night where you can.",
      sq: "Llogarite alkoolin zero: RAC jep kufirin 0,01%. Shpejtësia: 50 km/h në qytet nëse nuk ka tabelë tjetër, 80 km/h jashtë qytetit dhe 130 km/h në autostradë. Trekëndëshi i paralajmërimit është i detyrueshëm; rripat në çdo ulëse; fëmijët nën 12 vjeç jo përpara. Rrugët variojnë nga të mira në të dobëta, më keq në zona rurale dhe pas motit të keq, me rrezik rrëshqitjesh dheu dhe përmbytjesh, ndaj shmange ngasjen natën kur mundesh.",
    },
    source: SRC.rac,
    extraSource: SRC.fcdoSafety,
  },
  passport: {
    level: "know",
    title: { en: "Passport and stay", sq: "Pasaporta dhe qëndrimi" },
    body: {
      en: "UK and EU visitors can stay up to 90 days without a visa. Your passport must be undamaged and valid for the whole stay; no extra months are needed. Rules depend on your nationality, so check yours before you go.",
      sq: "Vizitorët nga Mbretëria e Bashkuar dhe BE mund të qëndrojnë deri në 90 ditë pa vizë. Pasaporta duhet të jetë e padëmtuar dhe e vlefshme për gjithë qëndrimin; nuk duhen muaj shtesë. Rregullat varen nga shtetësia, ndaj kontrolloje tëndën para nisjes.",
    },
    source: SRC.fcdoEntry,
  },
};

Object.assign(ROUTE_RULES, {
  safety: {
    level: "know",
    title: { en: "Staying safe", sq: "Siguria" },
    body: {
      en: "Kosovo is generally safe for visitors. The UK government notes a risk of protests, at times violent, in Zvečan, Zubin Potok, Leposavić and north Mitrovica, and a risk of landmines and unexploded weapons in some remote areas: on mountain hikes stay on marked trails. Use registered taxis ordered by phone or app, and keep an eye on bags at the airport and on buses.",
      sq: "Kosova në përgjithësi është e sigurt për vizitorët. Qeveria britanike përmend rrezik protestash, ndonjëherë të dhunshme, në Zveçan, Zubin Potok, Leposaviq dhe në veri të Mitrovicës, si dhe rrezik minash e mjetesh të pashpërthyera në disa zona të largëta: në shtigje malore qëndro në shtigjet e shënuara. Përdor taksi të regjistruara të porositura me telefon ose aplikacion dhe ki kujdes çantat në aeroport e në autobus.",
    },
    source: SRC.fcdoSafety,
  },
});

/**
 * The rules that apply to a route. `entry`/`exit` are ROUTE_PLACES; a car is
 * assumed whenever the entry is a land border.
 */
export function routeWarnings({ entry, exit }) {
  const from = ROUTE_PLACES.includes(entry) ? entry : "fly";
  const to = ROUTE_PLACES.includes(exit) ? exit : from;
  const ids = [];
  if (to === "serbia" && from !== "serbia") ids.push("serbiaExit");
  if (from !== "fly") ids.push("insurance", "drivingRules");
  ids.push("passport", "safety");
  return ids.map((id) => ({ id, ...ROUTE_RULES[id] }));
}

/** Map a quiz crossing to the country on the other side. */
export function entryFromCrossing(crossing, arrival) {
  if (arrival !== "drive") return "fly";
  return { kulle: "montenegro", merdare: "serbia", "hani-i-elezit": "north-macedonia", "vermice-morine": "albania" }[crossing] ?? "albania";
}

/* ------------------------------------------------------------- arrival */

const ARRIVAL = {
  fly: [
    {
      id: "bus",
      title: { en: "Airport bus 1A, every two hours", sq: "Autobusi 1A, çdo dy orë" },
      body: {
        en: "Trafiku Urban's line 1A leaves the airport at 08:00, 10:00, 12:00, 14:00, 16:00, 18:00, 20:00, 22:00 and 24:00, every day, and stops at Lakrishtë, Dardania, the Cathedral area and the main bus station. Towards the airport it leaves the bus station at 07:00 and every two hours until 23:00. A ticket costs €6 (paper) or €5 (digital / SMS). Allow about 40 minutes.",
        sq: "Linja 1A e Trafikut Urban niset nga aeroporti në 08:00, 10:00, 12:00, 14:00, 16:00, 18:00, 20:00, 22:00 dhe 24:00, çdo ditë, dhe ndalet në Lakrishtë, Dardani, te Katedralja dhe në stacionin e autobusëve. Drejt aeroportit niset nga stacioni i autobusëve në 07:00 dhe çdo dy orë deri në 23:00. Bileta kushton 6 € (letër) ose 5 € (digjitale / SMS). Llogarit rreth 40 minuta.",
      },
      source: SRC.airportBus,
    },
    {
      id: "taxi",
      title: { en: "Taxi to Prishtina", sq: "Taksi për në Prishtinë" },
      body: {
        en: "Expect roughly €15–25 to the centre, 20–25 minutes in normal traffic. Registered taxi firms are the safest choice and their fares are regulated; they are usually ordered by phone, and some have apps. Avoid drivers who approach you, and check the meter or agree the price before you set off.",
        sq: "Llogarit rreth 15–25 € deri në qendër, 20–25 minuta në trafik normal. Kompanitë e regjistruara të taksive janë zgjedhja më e sigurt dhe tarifat e tyre janë të rregulluara; zakonisht porositen me telefon, disa kanë aplikacion. Shmang shoferët që të afrohen vetë dhe kontrollo taksimetrin ose merruni vesh për çmimin para nisjes.",
      },
      source: SRC.airportGuide,
      extraSource: SRC.fcdoSafety,
    },
  ],
  drive: [
    {
      id: "insuranceDesk",
      title: { en: "First stop: the insurance desk", sq: "Ndalesa e parë: sporteli i sigurimit" },
      body: {
        en: "Unless your car has Albanian or North Macedonian plates, buy the border insurance at the crossing before driving on: €15 for 15 days or €20 for a month. It is sold at every crossing and at the bureau in Prishtina.",
        sq: "Nëse vetura nuk ka targa të Shqipërisë ose Maqedonisë së Veriut, bli sigurimin kufitar në pikë para se të vazhdosh: 15 € për 15 ditë ose 20 € për një muaj. Shitet në çdo pikë kufitare dhe në zyrën e Byrosë në Prishtinë.",
      },
      source: SRC.kib,
      extraSource: SRC.rac,
    },
    {
      id: "documents",
      title: { en: "Keep these in the car", sq: "Mbaji këto në makinë" },
      body: {
        en: "Driving licence, the car's registration and ownership papers, the insurance certificate and a warning triangle. A UK photocard licence is accepted; an old paper licence may also need an international permit. Right-hand-drive cars need headlamp converters unless the lights adjust.",
        sq: "Patentën, dokumentet e regjistrimit dhe të pronësisë së veturës, certifikatën e sigurimit dhe trekëndëshin e paralajmërimit. Patenta britanike me foto pranohet; një patentë e vjetër prej letre mund të kërkojë edhe leje ndërkombëtare. Veturat me timon djathtas duhet të kenë ngjitëse për dritat, nëse ato nuk rregullohen.",
      },
      source: SRC.rac,
      extraSource: SRC.fcdoSafety,
    },
  ],
  both: [
    {
      id: "sim",
      title: { en: "Mobile data", sq: "Interneti celular" },
      body: {
        en: "The two networks are Vala and IPKO, with shops in every town. At the airport there is a Vala kiosk in arrivals, open for incoming flights but closed by late evening. Every SIM is registered to an ID, so bring your passport; it takes about 15 minutes. Data packs cost a few euros, a little more at the airport than in town.",
        sq: "Dy rrjetet janë Vala dhe IPKO, me dyqane në çdo qytet. Në aeroport ka një kioskë të Valës te mbërritjet, e hapur për fluturimet që vijnë por e mbyllur vonë në mbrëmje. Çdo SIM regjistrohet me dokument, ndaj merr pasaportën; zgjat rreth 15 minuta. Paketat e internetit kushtojnë disa euro, pak më shtrenjtë në aeroport se në qytet.",
      },
      source: SRC.sim,
    },
    {
      id: "money",
      title: { en: "Money", sq: "Paratë" },
      body: {
        en: "Kosovo uses the euro. Cards work in most hotels, supermarkets and larger restaurants; carry some cash for small cafés, bakeries, markets and parking.",
        sq: "Kosova përdor euron. Kartelat pranohen në shumicën e hoteleve, supermarketeve dhe restoranteve më të mëdha; mbaj pak para në dorë për kafene të vogla, furra, tregje dhe parking.",
      },
      source: SRC.bqk,
    },
  ],
};

export function arrivalItems(arrival) {
  return [...(arrival === "drive" ? ARRIVAL.drive : ARRIVAL.fly), ...ARRIVAL.both];
}

/* -------------------------------------------------------------- prices */

export const PRICES = [
  { id: "cappuccino", label: { en: "Cappuccino", sq: "Kapuçino" }, eur: 1.68, source: SRC.numbeo },
  { id: "cheapMeal", label: { en: "Meal, inexpensive restaurant", sq: "Vakt në restorant të lirë" }, eur: 5, source: SRC.numbeo },
  { id: "dinnerForTwo", label: { en: "Dinner for two, mid-range", sq: "Darkë për dy, restorant mesatar" }, eur: 30, source: SRC.numbeo },
  { id: "beer", label: { en: "Local draught beer (0.5 L)", sq: "Birrë vendore (0,5 L)" }, eur: 2.5, source: SRC.numbeo },
  { id: "water", label: { en: "Bottled water (0.33 L)", sq: "Ujë në shishe (0,33 L)" }, eur: 0.94, source: SRC.numbeo },
  { id: "cityBus", label: { en: "Prishtina city bus ticket", sq: "Biletë autobusi urban në Prishtinë" }, eur: 0.8, source: SRC.cityBus },
  { id: "airportBus", label: { en: "Airport bus 1A", sq: "Autobusi i aeroportit 1A" }, eur: 6, source: SRC.airportBus },
  { id: "taxiStart", label: { en: "Taxi start + per km", sq: "Nisja e taksisë + për km" }, eur: 2, perKm: 0.5, source: SRC.numbeo },
  // Petrol and diesel come live from 383's daily fuel prices (components/xhep/help.tsx).
  { id: "skiPass", label: { en: "Brezovica day ski pass", sq: "Biletë ditore ski në Brezovicë" }, eur: 22, source: SRC.brezovicaPrices, interest: "skiing" },
];

export function pricesAreStale(now = new Date(), checkedAt = CHECKED_AT) {
  return (now.getTime() - Date.parse(checkedAt)) / 86_400_000 > PRICE_STALE_DAYS;
}

/* -------------------------------------------------------------- events */

/** Month/day ranges (inclusive). A range may wrap the year (Dec → Mar). */
export const EVENTS = [
  {
    id: "constitutionDay",
    from: [4, 9],
    to: [4, 9],
    title: { en: "Constitution Day (public holiday)", sq: "Dita e Kushtetutës (festë zyrtare)" },
    body: { en: "Public holiday; offices and some shops close.", sq: "Festë zyrtare; zyrat dhe disa dyqane mbyllen." },
    source: SRC.holidays,
  },
  {
    id: "labourDay",
    from: [5, 1],
    to: [5, 1],
    title: { en: "Labour Day (public holiday)", sq: "Dita e Punës (festë zyrtare)" },
    body: { en: "Public holiday.", sq: "Festë zyrtare." },
    source: SRC.holidays,
  },
  {
    id: "europeDay",
    from: [5, 9],
    to: [5, 9],
    title: { en: "Europe Day (public holiday)", sq: "Dita e Evropës (festë zyrtare)" },
    body: { en: "Public holiday.", sq: "Festë zyrtare." },
    source: SRC.holidays,
  },
  {
    id: "flagDay",
    from: [11, 28],
    to: [11, 28],
    title: { en: "Albanian Flag Day", sq: "Dita e Flamurit" },
    body: { en: "Not an official holiday in Kosovo, but widely celebrated with flags, music and gatherings.", sq: "Nuk është festë zyrtare në Kosovë, por festohet gjerësisht me flamuj, muzikë dhe tubime." },
    source: SRC.flagDay,
  },
  {
    id: "skiSeason",
    from: [12, 1],
    to: [3, 31],
    title: { en: "Ski season at Brezovica", sq: "Sezoni i skijimit në Brezovicë" },
    body: { en: "Kosovo's main ski resort in the Sharr Mountains usually runs from December to March, snow permitting. Day passes are around €22.", sq: "Qendra kryesore e skijimit në Malet e Sharrit zakonisht punon nga dhjetori deri në mars, nëse ka borë. Bileta ditore rreth 22 €." },
    source: SRC.brezovicaSeason,
    extraSource: SRC.brezovicaPrices,
    interest: "skiing",
  },
  {
    id: "christmasCatholic",
    from: [12, 25],
    to: [12, 25],
    title: { en: "Catholic Christmas (public holiday)", sq: "Krishtlindjet katolike (festë zyrtare)" },
    body: { en: "Public holiday; some shops and offices close.", sq: "Festë zyrtare; disa dyqane dhe zyra mbyllen." },
    source: SRC.holidays,
  },
  {
    id: "newYear",
    from: [12, 31],
    to: [1, 2],
    title: { en: "New Year (public holiday 1–2 January)", sq: "Viti i Ri (festë zyrtare 1–2 janar)" },
    body: { en: "Celebrations on New Year's Eve; 1 and 2 January are public holidays.", sq: "Festime natën e Vitit të Ri; 1 dhe 2 janari janë festa zyrtare." },
    source: SRC.holidays,
  },
  {
    id: "christmasOrthodox",
    from: [1, 7],
    to: [1, 7],
    title: { en: "Orthodox Christmas (public holiday)", sq: "Krishtlindjet ortodokse (festë zyrtare)" },
    body: { en: "Public holiday.", sq: "Festë zyrtare." },
    source: SRC.holidays,
  },
  {
    id: "independenceDay",
    from: [2, 17],
    to: [2, 17],
    title: { en: "Independence Day", sq: "Dita e Pavarësisë" },
    body: { en: "Kosovo's biggest celebration, marking the 2008 declaration of independence; expect crowds and events in Prishtina.", sq: "Festa më e madhe e Kosovës, në përvjetor të shpalljes së pavarësisë më 2008; prit turma dhe aktivitete në Prishtinë." },
    source: SRC.holidays,
  },
];

const dayOfYear = (month, day) => Date.UTC(2001, month - 1, day) / 86_400_000;

function inRange(month, day, from, to) {
  const d = dayOfYear(month, day);
  const a = dayOfYear(from[0], from[1]);
  const b = dayOfYear(to[0], to[1]);
  return a <= b ? d >= a && d <= b : d >= a || d <= b;
}

/**
 * Events overlapping the visitor's stay. With a start date, the exact days;
 * with only a month, the whole month. Nothing known → [].
 */
export function eventsFor({ startDate, month, days }) {
  const stay = [];
  if (typeof startDate === "string" && /^\d{4}-\d{2}-\d{2}$/.test(startDate)) {
    const start = Date.parse(`${startDate}T00:00:00Z`);
    const n = Math.min(60, Math.max(1, Number(days) || 1));
    for (let i = 0; i < n; i += 1) {
      const d = new Date(start + i * 86_400_000);
      stay.push([d.getUTCMonth() + 1, d.getUTCDate()]);
    }
  } else if (Number.isInteger(month) && month >= 1 && month <= 12) {
    const len = new Date(Date.UTC(2001, month, 0)).getUTCDate();
    for (let day = 1; day <= len; day += 1) stay.push([month, day]);
  } else {
    return [];
  }
  return EVENTS.filter((event) => stay.some(([m, d]) => inRange(m, d, event.from, event.to)));
}

/* ------------------------------------------------------------- phrases */

/** Show-to-a-local phrases. Albanian is the big line; English is the subtitle. */
export const PHRASES = [
  { id: "address", sq: "Më çoni te kjo adresë, ju lutem.", en: "Please take me to this address." },
  { id: "howMuch", sq: "Sa kushton?", en: "How much is it?" },
  { id: "bill", sq: "Llogarinë, ju lutem.", en: "The bill, please." },
  { id: "macchiato", sq: "Një makiato, ju lutem.", en: "A macchiato, please." },
  { id: "noMeat", sq: "Nuk ha mish.", en: "I don't eat meat." },
  { id: "noPork", sq: "Pa mish derri, ju lutem.", en: "No pork, please." },
  { id: "nutAllergy", sq: "Kam alergji nga arrat.", en: "I'm allergic to nuts." },
  { id: "pharmacy", sq: "Ku është barnatorja më e afërt?", en: "Where is the nearest pharmacy?" },
  { id: "doctor", sq: "Më duhet një mjek.", en: "I need a doctor." },
  { id: "ambulance", sq: "Thirrni ambulancën, ju lutem!", en: "Please call an ambulance!" },
  { id: "toilet", sq: "Ku është tualeti?", en: "Where is the toilet?" },
  { id: "english", sq: "A flisni anglisht?", en: "Do you speak English?" },
  { id: "slowly", sq: "Ju lutem, flisni ngadalë.", en: "Please speak slowly." },
  { id: "thanks", sq: "Faleminderit shumë!", en: "Thank you very much!" },
];
