"""Re-classify the cached article pool under the v2 stance definition.

The scraper only ever classifies cache misses, so without this the corrected
definition would take a full cache-retention window to take effect and the
existing pool would keep its v1 "is this good or bad news" labels forever.

Dry run by default — it prints what would change and writes nothing:

    py tools/tone_reclassify.py                 # report only
    py tools/tone_reclassify.py --limit 60      # cheaper sample
    py tools/tone_reclassify.py --write         # commit to the cache

`--write` rewrites public/tone-article-cache.json only. tone-outlets.json and
tone-history.json are regenerated by the next scraper run from that cache;
history rows older than the cache window keep their v1 labels and cannot be
recovered, which is why rows carry stanceVersion.
"""

import argparse
import json
import os
import sys
import time
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import tone_scraper as ts

# llama-3.3-70b is 12K tokens/minute on the free tier and a batch runs ~2K, so
# pace at roughly five batches a minute rather than discovering the limit.
BATCH_PAUSE_S = 12


def main() -> int:
    # Albanian reasons and German/French headlines go through this; the
    # Windows console defaults to cp1252 and dies on the first ç.
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="commit changes to the cache")
    ap.add_argument("--limit", type=int, default=0, help="only re-classify the first N")
    args = ap.parse_args()

    key = os.environ.get("GROQ_API_KEY")
    if not key:
        print("GROQ_API_KEY not set", file=sys.stderr)
        return 1
    from groq import Groq
    client = Groq(api_key=key)

    cache = ts.load_cache()
    entries = list(cache["articles"].values())
    if args.limit:
        entries = entries[: args.limit]
    print(f"{len(entries)} cached articles, model {ts.CLASSIFY_MODEL}\n")

    before = Counter(e.get("sentiment", "?") for e in entries)
    changes: list[tuple[str, str, str, str]] = []
    after = Counter()

    for i in range(0, len(entries), ts.CLASSIFY_BATCH_SIZE):
        chunk = entries[i : i + ts.CLASSIFY_BATCH_SIZE]
        items = [{"title": e["title"], "summary": e.get("summary", "")} for e in chunk]
        for entry, stance in zip(chunk, ts.classify_stance_batch(client, items)):
            old = entry.get("sentiment", "?")
            new = stance["stance"]
            after[new] += 1
            if old != new:
                changes.append((old, new, entry["title"][:70], stance["reason"][:60]))
            if args.write:
                entry.update({
                    "sentiment": new,
                    "stance": new,
                    "stanceReason": stance["reason"],
                    "isQuote": stance["isQuote"],
                    "speaker": stance["speaker"],
                    "evidence": stance["evidence"],
                    "confidence": stance["confidence"],
                    "model": ts.CLASSIFY_MODEL,
                    "stanceVersion": ts.STANCE_SCHEMA_VERSION,
                })
        done = min(i + ts.CLASSIFY_BATCH_SIZE, len(entries))
        print(f"  {done}/{len(entries)}", end="\r", flush=True)
        if done < len(entries):
            time.sleep(BATCH_PAUSE_S)

    total = sum(after.values()) or 1
    print("\n\nlabel distribution")
    print(f"  {'':10} {'before':>8} {'after':>8}")
    for label in ("positive", "neutral", "negative", ts.UNKNOWN):
        print(f"  {label:10} {before.get(label, 0):>8} {after.get(label, 0):>8}")
    print(f"\n{len(changes)} of {len(entries)} labels changed ({len(changes)/len(entries):.0%})")

    flipped = Counter(f"{o} -> {n}" for o, n, _, _ in changes)
    for move, count in flipped.most_common():
        print(f"  {move:24} {count}")

    print("\nsample of what moved:")
    for old, new, title, reason in changes[:12]:
        print(f"  {old:8} -> {new:8} {title}\n           {reason}")

    if args.write:
        # Same shape the scraper writes at the end of its run.
        ts.CACHE_PATH.write_text(
            json.dumps({"version": 1, "articles": cache["articles"]}, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        print(f"\nwritten to {ts.CACHE_PATH}")
    else:
        print("\ndry run — nothing written. Re-run with --write to commit.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
