"""Re-classify the cached article pool under the v2 stance definition.

The scraper only ever classifies cache misses, so without this the corrected
definition would take a full cache-retention window to take effect and the
existing pool would keep its v1 "is this good or bad news" labels forever.

Dry run by default — it prints what would change and writes nothing:

    py tools/tone_reclassify.py                 # report only
    py tools/tone_reclassify.py --limit 60      # cheaper sample
    py tools/tone_reclassify.py --write         # commit to the cache

`--write` rewrites public/tone-article-cache.json only. tone-outlets.json and
tone-history.json are regenerated by the next scraper run from that cache;
history rows older than the cache window keep their v1 labels and cannot be
recovered, which is why rows carry stanceVersion.
"""

import argparse
import json
import os
import re
import sys
import time
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import tone_scraper as ts

# llama-3.3-70b is 12K tokens/minute on the free tier and a batch runs ~2K, so
# pace at roughly five batches a minute rather than discovering the limit.
BATCH_PAUSE_S = 12


def main() -> int:
    # Albanian reasons and German/French headlines go through this; the
    # Windows console defaults to cp1252 and dies on the first ç.
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="commit changes to the cache")
    ap.add_argument("--limit", type=int, default=0, help="only re-classify the first N")
    ap.add_argument(
        "--only-foreign-reason",
        action="store_true",
        help="re-judge entries whose stanceReason is not Albanian. The "
             "rate-limit fallback to openai/gpt-oss-120b ignored the Albanian "
             "few-shots and wrote English reasons, which render straight into "
             "the UI on an Albanian site. Run this on the default model.",
    )
    ap.add_argument(
        "--only-unknown",
        action="store_true",
        help="retry just the entries left unresolved by an earlier run. Pair "
             "it with GROQ_CLASSIFY_MODEL=openai/gpt-oss-120b: a full 258-article "
             "backfill costs ~99K tokens and llama-3.3-70b only has 100K a day, "
             "so the tail of a big run rate-limits. gpt-oss-120b is a separate "
             "200K bucket.",
    )
    args = ap.parse_args()

    key = os.environ.get("GROQ_API_KEY")
    if not key:
        print("GROQ_API_KEY not set", file=sys.stderr)
        return 1
    from groq import Groq
    client = Groq(api_key=key)

    cache = ts.load_cache()
    entries = list(cache["articles"].values())
    if args.only_unknown:
        entries = [e for e in entries if e.get("stance", e.get("sentiment")) == ts.UNKNOWN]
    if args.only_foreign_reason:
        # Two weak signals, unioned, because neither is reliable alone on a
        # six-word phrase: the translator's Albanian-marker test misses short
        # Albanian that happens to contain no marker word, and a keyword test
        # trips over "neutral" and "media", which are spelled the same in both
        # languages. Over-inclusion is cheap — re-judging an entry that was
        # already fine just reproduces it.
        english_only = re.compile(
            r"\b(the|of|without|toward|towards|uses|factual|loaded|contempt|"
            r"describes?|coverage|hostile|report(s|ing|ed)?)\b",
            re.I,
        )
        entries = [
            e for e in entries
            if not ts.is_albanian_text(e.get("stanceReason") or "")
            or english_only.search(e.get("stanceReason") or "")
        ]
    if args.limit:
        entries = entries[: args.limit]
    if not entries:
        print("nothing to do")
        return 0
    print(f"{len(entries)} cached articles, model {ts.CLASSIFY_MODEL}\n")

    before = Counter(e.get("sentiment", "?") for e in entries)
    changes: list[tuple[str, str, str, str]] = []
    after = Counter()

    for i in range(0, len(entries), ts.CLASSIFY_BATCH_SIZE):
        chunk = entries[i : i + ts.CLASSIFY_BATCH_SIZE]
        items = [{"title": e["title"], "summary": e.get("summary", "")} for e in chunk]
        for entry, stance in zip(chunk, ts.classify_stance_batch(client, items)):
            old = entry.get("sentiment", "?")
            new = stance["stance"]
            after[new] += 1
            if old != new:
                changes.append((old, new, entry["title"][:70], stance["reason"][:60]))
            if args.write:
                entry.update({
                    "sentiment": new,
                    "stance": new,
                    "stanceReason": stance["reason"],
                    "isQuote": stance["isQuote"],
                    "speaker": stance["speaker"],
                    "evidence": stance["evidence"],
                    "confidence": stance["confidence"],
                    "model": ts.CLASSIFY_MODEL,
                    "stanceVersion": ts.STANCE_SCHEMA_VERSION,
                })
        done = min(i + ts.CLASSIFY_BATCH_SIZE, len(entries))
        print(f"  {done}/{len(entries)}", end="\r", flush=True)
        if done < len(entries):
            time.sleep(BATCH_PAUSE_S)

    total = sum(after.values()) or 1
    print("\n\nlabel distribution")
    print(f"  {'':10} {'before':>8} {'after':>8}")
    for label in ("positive", "neutral", "negative", ts.UNKNOWN):
        print(f"  {label:10} {before.get(label, 0):>8} {after.get(label, 0):>8}")
    print(f"\n{len(changes)} of {len(entries)} labels changed ({len(changes)/len(entries):.0%})")

    flipped = Counter(f"{o} -> {n}" for o, n, _, _ in changes)
    for move, count in flipped.most_common():
        print(f"  {move:24} {count}")

    print("\nsample of what moved:")
    for old, new, title, reason in changes[:12]:
        print(f"  {old:8} -> {new:8} {title}\n           {reason}")

    if args.write:
        # Same shape the scraper writes at the end of its run.
        ts.CACHE_PATH.write_text(
            json.dumps({"version": 1, "articles": cache["articles"]}, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        print(f"\nwritten to {ts.CACHE_PATH}")
        rederive(cache["articles"])
    return 0


def rederive(articles: dict) -> None:
    """Rebuild tone-outlets.json from the cache.

    Without this the cache holds v2 labels while the summaries the site reads
    still hold v1 indices, so every country renders at its old colour until
    the next scheduled scrape. Grouping is by the cache's own `country`, which
    is where an article was first seen — the scraper's per-country attribution
    is richer, and its next run supersedes this.
    """
    countries: dict[str, dict] = {}
    summaries: dict[str, dict] = {}
    for country in ts.FEEDS:
        mine = [a for a in articles.values() if a.get("country") == country]
        by_outlet: dict[str, list[dict]] = {}
        for a in mine:
            by_outlet.setdefault(a.get("outlet", "?"), []).append({
                "title": a["title"], "albanianTitle": a.get("albanianTitle"),
                "url": a["url"], "date": a.get("date", ""),
                "sentiment": a.get("stance", a.get("sentiment")),
                "reason": a.get("stanceReason", ""), "isQuote": bool(a.get("isQuote")),
                "speaker": a.get("speaker", ""), "evidence": a.get("evidence", ""),
            })

        outlets = []
        for name, arts in sorted(by_outlet.items()):
            arts = arts[:6]
            scored = [x for x in arts if x["sentiment"] in ts.VALID_STANCES]
            vote = Counter(x["sentiment"] for x in scored).most_common(1)[0][0] if scored else ts.UNKNOWN
            outlets.append({"name": name, "sentiment": vote, "articleCount": len(arts), "articles": arts})

        counts = Counter(a.get("stance", a.get("sentiment")) for a in mine)
        pos, neu, neg = counts.get("positive", 0), counts.get("neutral", 0), counts.get("negative", 0)
        n = pos + neu + neg
        summary = {
            "index": ts.country_index(pos, neu, neg),
            "positive": round(100 * pos / n) if n else 0,
            "neutral": round(100 * neu / n) if n else 0,
            "negative": round(100 * neg / n) if n else 0,
            "n": n,
            "excluded": counts.get(ts.UNKNOWN, 0),
            "confident": ts.is_confident(n, counts.get(ts.UNKNOWN, 0)),
            "stanceVersion": ts.STANCE_SCHEMA_VERSION,
        }
        countries[country] = {"outlets": outlets, "summary": summary}
        summaries[country] = summary

    total = sum(s["n"] for s in summaries.values())
    weighted = sum(s["index"] * s["n"] for s in summaries.values() if s["index"] is not None)
    overall = round(weighted / total) if total else None

    ts.OUTLETS_PATH.write_text(
        json.dumps({
            "lastUpdated": max((a.get("lastSeen", "") for a in articles.values()), default=""),
            "overallIndex": overall,
            "totalArticles": total,
            "sourceCount": sum(len(c["outlets"]) for c in countries.values()),
            "countries": countries,
            "stanceVersion": ts.STANCE_SCHEMA_VERSION,
        }, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    # The homepage module reads its summary from the history, not from the
    # outlets file, so re-deriving only the latter leaves every country
    # rendering at its old colour. Upsert today's row here too.
    #
    # Earlier rows are deliberately left alone: they were produced under the
    # v1 definition and the articles behind them have aged out of the cache,
    # so they cannot be recomputed. They keep stanceVersion 1, and the trend
    # chart is expected to mark the boundary rather than pretend one
    # continuous line means one continuous thing.
    today = max((a.get("lastSeen", "") for a in articles.values()), default="")
    history = json.loads(ts.HISTORY_PATH.read_text("utf-8")) if ts.HISTORY_PATH.exists() else []
    history = [row for row in history if row.get("date") != today]
    picked = [a for a in articles.values() if a.get("stance") in ("positive", "negative")][:6]
    history.append({
        "date": today,
        "overallIndex": overall,
        "totalArticles": total,
        "sourceCount": sum(len(c["outlets"]) for c in countries.values()),
        "countries": summaries,
        "stanceVersion": ts.STANCE_SCHEMA_VERSION,
        "headlines": [{
            "title": a["title"], "source": a.get("outlet", ""), "country": a.get("country", ""),
            "flag": ts.FLAGS.get(a.get("country", ""), ""), "url": a["url"],
            "sentiment": a.get("stance"),
        } for a in picked],
    })
    history.sort(key=lambda r: r.get("date", ""))
    ts.HISTORY_PATH.write_text(json.dumps(history[-ts.HISTORY_DAYS:], ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"\nrederived {ts.OUTLETS_PATH.name} + {ts.HISTORY_PATH.name}: overall {overall}")
    for country, s in summaries.items():
        # index is None for a country with no scored articles yet — format it
        # as a dash rather than crashing the report after the files are written.
        idx = "—" if s["index"] is None else s["index"]
        print(f"  {country:10} {idx:>4}  (n={s['n']}, +{s['positive']}% ={s['neutral']}% -{s['negative']}%)")
    else:
        print("\ndry run — nothing written. Re-run with --write to commit.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
