-- 0052 — Dosje seed: the existing timeline, as drafts.
--
-- Generated by scripts/dosje_seed.mjs from lib/topics.mjs. Do not hand-edit;
-- regenerate.
--
-- Every milestone enters as 'draft' and none is publicly readable. Two of them
-- carry a source string in the old data and it is preserved as a citation with
-- no http_status, which deliberately does not count toward the two-publisher
-- minimum until it has actually been fetched.
--
-- Applying this migration renders the dossier empty. That is expected.


insert into public.dosje_topics (slug, title, blurb, status, anchors, signals, excludes)
values ('dialogu-kosove-serbi', 'Dialogu Kosovë–Serbi', 'Bisedimet e ndërmjetësuara nga BE-ja, marrëveshjet e arritura dhe zbatimi i tyre.', 'draft', array['dialogu kosove serbi', 'kosove serbi', 'kosova serbia', 'ohri', 'ohrit', 'normalizim', 'normalizimit', 'asociacioni', 'asociacionin', 'vucic', 'petkovic', 'lajcak', 'mitrovica', 'veriu i kosoves', 'targat', 'banjska', 'banjske', 'dinar', 'dinarit']::text[], array['bruksel', 'brukselit']::text[], '{}'::text[])
on conflict (slug) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '1999-06-01', 'month', 'Qershor 1999', 'Baza',
        'Lufta përfundon dhe hyn në fuqi Rezoluta 1244', 'Pas fushatës ajrore të NATO-s, forcat serbe tërhiqen nga Kosova. Këshilli i Sigurimit miraton Rezolutën 1244, që vendos administrim ndërkombëtar dhe një prani ushtarake të udhëhequr nga NATO.', 'Është teksti që Beogradi citon ende sot kur kundërshton vendimet e Prishtinës, dhe baza ligjore e pranisë së KFOR-it.', 'draft', 'hand-written (pre-pipeline)', 'lufta-perfundon-dhe-hyn-ne-fuqi-rezoluta-1244')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2008-02-17', 'day', '17 shkurt 2008', 'Pavarësia',
        'Kosova shpall pavarësinë', 'Kuvendi i Kosovës shpall pavarësinë. Serbia nuk e njeh dhe nis një fushatë të gjatë diplomatike kundër njohjeve të reja.', 'Mosnjohja është burimi i çdo bllokimi të mëvonëshëm, nga anëtarësimet ndërkombëtare te kodi telefonik.', 'draft', 'hand-written (pre-pipeline)', 'kosova-shpall-pavaresine')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2010-07-22', 'day', '22 korrik 2010', 'GJND',
        'Gjykata Ndërkombëtare e Drejtësisë jep opinionin', 'GJND-ja vlerëson se shpallja e pavarësisë nuk shkeli të drejtën ndërkombëtare. Opinioni është këshillimor dhe nuk shprehet për statusin.', 'Hapi rrugën për dialogun: pas tij, Asambleja e OKB-së ia kaloi çështjen BE-së.', 'draft', 'hand-written (pre-pipeline)', 'gjykata-nderkombetare-e-drejtesise-jep-opinionin')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2011-03-01', 'month', 'Mars 2011', 'Nisja',
        'Dialogu teknik nis në Bruksel', 'Nis raundi i parë i bisedimeve të ndërmjetësuara nga BE-ja, për çështje praktike: lëvizja e lirë, kadastra, diplomat, vulat doganore.', 'Ky format, BE-ja si ndërmjetëse e jo si arbitre, mbetet korniza brenda së cilës zhvillohet çdo bisedim edhe sot.', 'draft', 'hand-written (pre-pipeline)', 'dialogu-teknik-nis-ne-bruksel')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2011-07-01', 'month', 'Korrik–shtator 2011', 'Kriza',
        'Kriza e pikave kufitare në veri', 'Prishtina dërgon njesi speciale për të marrë kontrollin e pikave Jarinje dhe Bërnjak. Pasojnë barrikada, djegia e një pike kufitare dhe ndërhyrja e KFOR-it.', 'Modeli u përsërit për një dekadë: një vendim administrativ në veri kthehet në krizë sigurie brenda ditesh.', 'draft', 'hand-written (pre-pipeline)', 'kriza-e-pikave-kufitare-ne-veri')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2012-10-01', 'month', 'Tetor 2012', 'Niveli politik',
        'Dialogu ngrihet në nivel kryeministrash', 'Bisedimet kalojnë nga niveli teknik në atë politik, me takime të drejtpërdrejta mes kryeministrave të dy vendeve.', 'Pa këtë ngritje nuk do të kishte pasur Marrëveshje të Parë gjashtë muaj më vonë.', 'draft', 'hand-written (pre-pipeline)', 'dialogu-ngrihet-ne-nivel-kryeministrash')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2013-04-19', 'day', '19 prill 2013', 'Marrëveshje',
        'Marrëveshja e Parë e Brukselit', 'Pas gjashtë muajsh bisedimesh në nivel kryeministrash, palët bien dakord për peswëmbedhjetë pika. Strukturat paralele të sigurisë në veri shpërbehen dhe policia e gjyqësori integrohen në sistemin e Kosovës, me një komandant rajonal serb për katër komunat veriore. Në këmbëngulje të Beogradit, teksti parasheh edhe një Asociacion të komunave me shumicë serbe. Asnjëra palë nuk pranon se marrëveshja prek statusin.', 'Është dokumenti bazë i gjithë dialogut. Çdo bisedim i mëvonëshëm i referohet atij, dhe pika e Asociacionit mbetet e pazbatuar.', 'draft', 'hand-written (pre-pipeline)', 'marreveshja-e-pare-e-brukselit')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2013-11-01', 'month', 'Nëntor 2013', 'Integrimi',
        'Zgjedhjet lokale mbahen edhe në veri', 'Për herë të parë zgjedhjet lokale mbahen në katër komunat veriore sipas ligjit të Kosovës, pas thirrjes së Beogradit për pjesëmarrje.', 'Ishte prova e parë praktike se Marrëveshja e Parë mund të zbatohej në terren.', 'draft', 'hand-written (pre-pipeline)', 'zgjedhjet-lokale-mbahen-edhe-ne-veri')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2015-08-25', 'day', '25 gusht 2015', 'Asociacioni',
        'Parimet e Asociacionit dhe marrëveshjet për energjinë', 'Arrihet pajtimi për parimet e përgjithshme të Asociacionit të komunave me shumicë serbe, së bashku me marrëveshje për energjinë, telekomin dhe urën e Mitrovicës.', 'Teksti u bë menjëherë i diskutueshem brenda Kosovës, dhe mbetet nyja më e ngurtë e të gjithë procesit.', 'draft', 'hand-written (pre-pipeline)', 'parimet-e-asociacionit-dhe-marreveshjet-per-energjine')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2015-12-01', 'month', 'Dhjetor 2015', 'Kushtetuta',
        'Gjykata Kushtetuese vlerëson parimet e Asociacionit', 'Gjykata Kushtetuese e Kosovës konstaton se disa nga parimet e dakorduara nuk janë plotësisht në pajtim me Kushtetutën.', 'Ky vendim është arsyeja juridike që Prishtina përmend sa herë kërkohet zbatimi i menjëhershëm i Asociacionit.', 'draft', 'hand-written (pre-pipeline)', 'gjykata-kushtetuese-vlereson-parimet-e-asociacionit')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2017-01-01', 'month', 'Janar 2017', 'Incident',
        'Treni me mbishkrimin “Kosova është Serbi”', 'Një tren i nisur nga Beogradi drejt Mitrovicës, i lyer me mbishkrimin “Kosova është Serbi” në njezet gjuhë, ndalet në kufi dhe kthehet.', 'Tregoi se simbolika, jo vetëm politika, mjafton për të ngrirë dialogun për muaj të terë.', 'draft', 'hand-written (pre-pipeline)', 'treni-me-mbishkrimin-kosova-eshte-serbi')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2018-11-01', 'month', 'Nëntor 2018', 'Taksa',
        'Kosova vendos takën 100 për qind ndaj mallrave serbe', 'Pas dështimit të anëtarësimit në Interpol, Qeveria e Kosovës vendos takë doganore 100 për qind ndaj mallrave nga Serbia dhe Bosnja.', 'Dialogu u ndal për më shumë se një vit e gjysmë: pa heqjen e takës, Beogradi refuzoi të ulej në tavolinë.', 'draft', 'hand-written (pre-pipeline)', 'kosova-vendos-taken-100-per-qind-ndaj-mallrave-serbe')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2020-04-01', 'month', 'Prill 2020', 'Taksa',
        'Taksa hiqet', 'Pas presionit të fortë amerikan dhe evropian, taksa hiqet në faza gjatë pranëverës së 2020-tës.', 'Heqja ishte kushti për rinisjen e bisedimeve, dhe çoi drejtpërdrejt te takimi i Uashingtonit.', 'draft', 'hand-written (pre-pipeline)', 'taksa-hiqet')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2020-09-04', 'day', '4 shtator 2020', 'Uashington',
        'Marrëveshjet e Uashingtonit', 'Në Shtëpinë e Bardhë, Kosova dhe Serbia nënshkruajnë veçmas dy dokumente pothuajse identike për normalizim ekonomik: autostrada dhe hekurudha lidhëse, njohje reciproke e diplomave, pjesëmarrje në mini-Schengenin rajonal dhe bashkëpunim energjetik. Dokumentet përmbajnë edhe pika që nuk kanë lidhje me njera-tjetrën, si zhvendosja e ambasadave në Jerusalem.', 'Shënoi hyrjen e Uashingtonit si tavolinë paralele me Brukselin, jo gjithnjë me të njëjtin drejtim.', 'draft', 'hand-written (pre-pipeline)', 'marreveshjet-e-uashingtonit')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2021-09-01', 'month', 'Shtator 2021', 'Targat',
        'Kriza e parë e targave', 'Vendimi për targa të përkohshme për automjetet me targa serbe sjell barrikada në veri dhe një bllokim dyjavesh të pikave kufitare.', 'Nisi ciklin e krizave të targave që do të dominonte dy vitet në vijim.', 'draft', 'hand-written (pre-pipeline)', 'kriza-e-pare-e-targave')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2022-08-01', 'month', 'Gusht–nëntor 2022', 'Targat',
        'Kriza e targave rikthehet dhe serbët dalin nga institucionet', 'Afati për riregjistrimin e automjeteve me targa serbe sjell barrikada të reja në veri dhe ndërhyrje të KFOR-it në rrugët kryesore. Në nëntor, rreth gjashtëqind zyrtarë serbë — policë, gjyqtarë, prokurorë dhe anëtarë të kuvendeve komunale — japin dorëheqje të njehkohshme, duke lënë katër komuna pa administratë funksionale.', 'Dorëheqjet krijuan zbrazëtinë institucionale që çoi te zgjedhjet e kontestuara të vitit 2023.', 'draft', 'hand-written (pre-pipeline)', 'kriza-e-targave-rikthehet-dhe-serbet-dalin-nga-institucionet')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2023-02-27', 'day', '27 shkurt 2023', 'Marrëveshje',
        'Marrëveshja për rrugën drejt normalizimit', 'Teksti i njembedhjetë neneve parasheh njohje reciproke të dokumenteve dhe simboleve, mosbllokim të anëtarësimeve ndërkombëtare, dhe një nivel të përshtatshëm vetëqeverisjeje për komunitetin serb në Kosovë. Asnjëra palë nuk e nënshkruan: Prishtina kërkon nënshkrim, Beogradi refuzon, dhe BE-ja e trajton si të detyrueshëm politikisht pavarësisht mungeses së firmave.', 'Mosnënshkrimi është arsyeja që të dyja palët e lexojnë tekstin ndryshe deri sot.', 'draft', 'hand-written (pre-pipeline)', 'marreveshja-per-rrugen-drejt-normalizimit')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2023-03-18', 'day', '18 mars 2023', 'Ohri',
        'Aneksi i zbatimit në Ohër', 'Në Ohër të Maqedonisë së Veriut, palët bien dakord për aneksin që përcakton se si zbatohet marrëveshja e shkurtit.', 'Aneksi hoqi radhën e hapave, por jo detyrimin për nënshkrim, prandaj zbatimi mbeti çështje interpretimi.', 'draft', 'hand-written (pre-pipeline)', 'aneksi-i-zbatimit-ne-oher')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2023-05-01', 'month', 'Maj 2023', 'Përplasje',
        'Kryetarët hyjnë në komunat veriore dhe ushtarë të KFOR-it lëndohen', 'Pas zgjedhjeve me pjesëmarrje nën tre për qind, kryetarët e rinj hyjnë në godinat komunale me shoqërim policor. Më 29 maj, dhjetëra ushtarë të KFOR-it lëndohen në përballje me protestues.', 'Ishte hera e parë pas shumë vitesh që trupat e NATO-s pësuan lëndime të shumta, dhe solli masa ndëshkuese të BE-së ndaj Prishtinës.', 'draft', 'hand-written (pre-pipeline)', 'kryetaret-hyjne-ne-komunat-veriore-dhe-ushtare-te-kfor-it-lendohen')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2023-09-24', 'day', '24 shtator 2023', 'Banjskë',
        'Sulmi i armatosur në Banjskë', 'Një grup i armatosur i zihet presë policisë së Kosovës te Banjska e Zveçanit. Vritet një polic i Kosovës dhe tre sulmues; gjendet një arsenal i konsiderueshem armatimi.', 'Ndryshoi tonin e dialogut dhe çoi në rritje të pranisë ndërkombëtare të sigurisë në veri.', 'draft', 'hand-written (pre-pipeline)', 'sulmi-i-armatosur-ne-banjske')
on conflict (topic_slug, dedupe_key) do nothing;

-- Recorded as provenance, not as a verified citation: no url, no fetch, so it
-- cannot satisfy the two-publisher rule.
insert into public.dosje_citations (milestone_id, url, publisher, source_title)
select id, 'https://example.invalid/unverified', 'Balkan Insight; RFE/RL', 'burim i deklaruar, i paverifikuar'
  from public.dosje_milestones
 where topic_slug = 'dialogu-kosove-serbi' and dedupe_key = 'sulmi-i-armatosur-ne-banjske'
on conflict (milestone_id, url) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('dialogu-kosove-serbi', date '2024-02-01', 'month', 'Shkurt 2024', 'Dinari',
        'Rregullorja e Bankës Qendrore për paranë e gatshme', 'Hyn në fuqi rregullorja që përcakton euron si të vetëmen monedhë për pagesa në para të gatshme, duke prekur pagesat në dinarë për komunitetin serb.', 'U kritikua nga partnerët ndërkombëtarë për mungese periudhe kalimtare, dhe u bë tema kryesore e dialogut atë vit.', 'draft', 'hand-written (pre-pipeline)', 'rregullorja-e-bankes-qendrore-per-parane-e-gatshme')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_topics (slug, title, blurb, status, anchors, signals, excludes)
values ('kfor', 'KFOR-i në Kosovë', 'Prania ushtarake e NATO-s, mandati i saj dhe roli në situatat e sigurisë.', 'draft', array['kfor', 'paqeruajtes', 'ura mbi iber', 'iber', 'zvecan', 'zvecani']::text[], array['nato']::text[], '{}'::text[])
on conflict (slug) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('kfor', date '1999-06-01', 'month', 'Qershor 1999', 'Mandati',
        'KFOR-i vendoset në Kosovë', 'Pas fushatës ajrore të NATO-s dhe tërheqjes së forcave serbe, Këshilli i Sigurimit miraton Rezolutën 1244 dhe autorizon një prani ndërkombëtare sigurie. Rreth 50 mijë trupa nga më shumë se tridhjetë shtete hyjnë në Kosovë, të ndarë në pesë zona përgjegjësie. Detyra e parë është ndalja e armiqesive, çarmatimi i formacioneve të armatosura dhe kthimi i qindra mijë njerezve të zhvendosur. Nga ky moment siguria në Kosovë nuk është më çështje e Beogradit.', 'Mandati i vitit 1999 është ende baza ligjore e pranisë së KFOR-it sot, pavarësisht ndryshimit të madh të kontekstit.', 'draft', 'hand-written (pre-pipeline)', 'kfor-i-vendoset-ne-kosove')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('kfor', date '2004-03-17', 'day', '17–18 mars 2004', 'Trazirat',
        'Trazirat e marsit', 'Dy ditë dhune ndëretnike shpërthejnë pas raportimeve të pavertetuara se tre fëmijë shqiptarë ishin mbytur në Ibër. Vriten nendëmbedhjetë veta — njembedhjetë shqiptarë dhe tetë serbë — dhe më shumë se nenteqind mbeten të plagosur. Rreth katër mijë njerez zhvendosen, pesëqind e pesedhjetë shtëpi shkatërrohen dhe njezetë e shtatë kisha e manastire ortodokse digjen.', 'KFOR-i dhe policia ndërkombëtare u kritikuan ashër për reagim të ngadaltë dhe për mungese të një zinxhiri të vetëm komandimi; pas 2004-ës doktrina e forcës ndryshoi.', 'draft', 'hand-written (pre-pipeline)', 'trazirat-e-marsit')
on conflict (topic_slug, dedupe_key) do nothing;

-- Recorded as provenance, not as a verified citation: no url, no fetch, so it
-- cannot satisfy the two-publisher rule.
insert into public.dosje_citations (milestone_id, url, publisher, source_title)
select id, 'https://example.invalid/unverified', 'Human Rights Watch, “Failure to Protect” (2004)', 'burim i deklaruar, i paverifikuar'
  from public.dosje_milestones
 where topic_slug = 'kfor' and dedupe_key = 'trazirat-e-marsit'
on conflict (milestone_id, url) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('kfor', date '2008-02-01', 'month', 'Shkurt 2008', 'Statusi',
        'KFOR-i mbetet pas shpalljes së pavarësisë', 'Me shpalljen e pavarësisë, NATO konfirmon se KFOR-i qendron dhe se baza e mandatit mbetet Rezoluta 1244, jo ftesa e një shteti të ri. Kjo zgjedhje mban brenda aleancës edhe shtetet që nuk e njohin Kosovën, sepse asnjëra nuk detyrohet të ndryshojë qendrim për të mbajtur trupat në terren. Prandaj KFOR-i nuk është forcë e Kosovës, nuk merr urdhëra nga Prishtina dhe raporton në Bruksel.', 'Prandaj KFOR-i nuk është forcë e Kosovës dhe nuk merr urdhera nga Prishtina.', 'draft', 'hand-written (pre-pipeline)', 'kfor-i-mbetet-pas-shpalljes-se-pavaresise')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('kfor', date '2013-01-01', 'year', '2013', 'Zvogëlimi',
        'Forca zvogëlohet në rreth pesë mijë trupa', 'Pas disa vitesh me përmirësim të gjendjes, NATO kalon nga një prani e madhe e përhershme në një forcë të vogël me rezerva të vendosura jashtë vendit. Numri bie në rreth pesë mijë trupa dhe shumë baza dorëzohen. Modeli mbeshtetet te supozimi se përforcimet mund të mbërrijnë brenda ditesh, gjë që do të testohet seriozisht një dekadë më vonë.', 'Zvogëlimi shpjegon pse çdo krizë e mëvonshme kërkon dërgim të shpejtë forcash shtesë nga jashtë.', 'draft', 'hand-written (pre-pipeline)', 'forca-zvogelohet-ne-rreth-pese-mije-trupa')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('kfor', date '2023-05-29', 'day', '29 maj 2023', 'Përplasje',
        'Ushtarë të KFOR-it lëndohen në veri', 'Pas zgjedhjeve lokale me pjesëmarrje nën tre për qind, kryetarët e rinj hyjnë në godinat komunale të veriut me shoqërim policor. Protestat përshkallezohen para komunës së Zveçanit dhe dhjetëra ushtarë italianë e hungarezë të KFOR-it lëndohen, disa rëndësisht. NATO dërgon menjëherë rreth pesëqind trupa shtesë, ndersa BE-ja vendos masa ndaj Prishtinës për mënyrën si u veprua.', 'Ishte hera e parë pas shumë vitesh që trupat e NATO-s pësuan lëndime të shumta në Kosovë.', 'draft', 'hand-written (pre-pipeline)', 'ushtare-te-kfor-it-lendohen-ne-veri')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('kfor', date '2023-09-01', 'month', 'Shtator–tetor 2023', 'Përforcim',
        'Forca shtesë pas Banjskës', 'Sulmi i armatosur në Banjskë, ku u vra një polic i Kosovës dhe u gjet një sasi e madhe armatimi, ndryshon vlerësimin e riskut. NATO dërgon batalione shtesë, rrit patrullimin në veri dhe kthen në Kosovë pajisje të rënda që ishin tërhequr vite më parë. Prania e sotme e KFOR-it, më e madhe se në një dekadë, është pasojë e drejtpërdrejtë e vjeshtës 2023.', 'Prania e sotme e KFOR-it është pasojë e drejtpërdrejtë e vjeshtës 2023.', 'draft', 'hand-written (pre-pipeline)', 'forca-shtese-pas-banjskes')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_topics (slug, title, blurb, status, anchors, signals, excludes)
values ('anetaresimi-ne-be', 'Rruga e Kosovës drejt BE-së', 'Marrëveshjet, aplikimi për anëtarësim, vizat dhe kushtëzimet.', 'draft', array['bashkimi evropian', 'bashkimin evropian', 'anetaresim', 'anetaresimi', 'integrim evropian', 'stabilizim asociim', 'vizave', 'komisioni evropian', 'parlamenti evropian', 'eulex', 'kandidate']::text[], array['be-ja', 'be-se', 'liberalizim', 'kandidat']::text[], '{}'::text[])
on conflict (slug) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('anetaresimi-ne-be', date '2008-12-01', 'month', 'Dhjetor 2008', 'EULEX',
        'Misioni EULEX vendoset në Kosovë', 'BE-ja vendos misionin më të madh civil të saj, me mandat në polici, drejtësi dhe dogana.', 'EULEX-i ishte forma e parë konkrete e pranisë evropiane, dhe modeli i saj u bë i diskutueshëm për vite.', 'draft', 'hand-written (pre-pipeline)', 'misioni-eulex-vendoset-ne-kosove')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('anetaresimi-ne-be', date '2015-10-01', 'month', 'Tetor 2015', 'MSA',
        'Marrëveshja e Stabilizim-Asociimit nënshkruhet', 'Pas një studimi fizibiliteti dhe negociatash disavjeçare, MSA-ja nënshkruhet në Strasburg.', 'Ishte marrëveshja e parë kontraktuale mes Kosovës dhe BE-së, e nënshkruar pa u kërkuar njohje nga të pesë shtënë anëtare mosnjohëse.', 'draft', 'hand-written (pre-pipeline)', 'marreveshja-e-stabilizim-asociimit-nenshkruhet')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('anetaresimi-ne-be', date '2016-04-01', 'day', '1 prill 2016', 'MSA',
        'MSA-ja hyn në fuqi', 'Marrëveshja hyn në fuqi dhe krijon kornizën ligjore të marrëdhënies, me detyrime konkrete për reforma.', 'Është hapi që e kthen raportin me BE-në nga politikë ndihme në detyrime të ndërsjella.', 'draft', 'hand-written (pre-pipeline)', 'msa-ja-hyn-ne-fuqi')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('anetaresimi-ne-be', date '2018-07-01', 'month', 'Korrik 2018', 'Vizat',
        'Komisioni konfirmon plotësimin e kritereve për viza', 'Komisioni Evropian konstaton se Kosova i ka përmbushur të gjitha kriteret për liberalizim vizash, përfshirë demarkacionin me Malin e Zi.', 'Mes këtij konfirmimi dhe heqjes reale të vizave kaluan më shumë se pesë vjet bllokimi në Këshill.', 'draft', 'hand-written (pre-pipeline)', 'komisioni-konfirmon-plotesimin-e-kritereve-per-viza')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('anetaresimi-ne-be', date '2022-12-14', 'day', '14 dhjetor 2022', 'Aplikimi',
        'Kosova aplikon për anëtarësim në BE', 'Qeveria e Kosovës dorëzon aplikimin formal për anëtarësim në Pragen, presidenën e radhës të Këshillit. Aplikimi vjen pak ditë pas hyrjes në fuqi të marrëveshjes për targat dhe në një moment kur pesë shtete anëtare ende nuk e njohin pavarësinë, çka do të thotë se edhe hapi i parë procedural kërkon unanimitet që nuk ekziston.', 'Aplikimi mbetet pa statusin e vendit kandidat, çka e bën rrugën e Kosovës të ndryshme nga fqinjët.', 'draft', 'hand-written (pre-pipeline)', 'kosova-aplikon-per-anetaresim-ne-be')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('anetaresimi-ne-be', date '2023-06-01', 'month', 'Qershor 2023', 'Masat',
        'BE-ja vendos masa ndaj Kosovës', 'Pas krizes së majit në veri, BE-ja pezullon disa programe dhe takime të nivelit të lartë me Prishtinën.', 'Ishte hera e parë që Brukseli përdori masa ndëshkuese ndaj një vendi aspirant të Ballkanit Përendimor.', 'draft', 'hand-written (pre-pipeline)', 'be-ja-vendos-masa-ndaj-kosoves')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('anetaresimi-ne-be', date '2024-01-01', 'day', '1 janar 2024', 'Vizat',
        'Liberalizimi i vizave hyn në fuqi', 'Qytetarët e Kosovës me pasaportë biometrike mund të udhëtojnë pa viza në zonën Schengen për nentëdhjetë ditë brenda çdo periudhe njeqind e tetëdhjetë ditore. Kosova ishte vendi i fundit i Ballkanit Përendimor pa këtë të drejtë, më shumë se pesë vjet pasi Komisioni kishte konfirmuar se të gjitha kriteret ishin përmbushur.', 'Kosova ishte e fundit në rajon që e fitoi këtë të drejtë, pas më shumë se një dekade pritjeje.', 'draft', 'hand-written (pre-pipeline)', 'liberalizimi-i-vizave-hyn-ne-fuqi')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_topics (slug, title, blurb, status, anchors, signals, excludes)
values ('diaspora', 'Diaspora dhe të drejtat e saj', 'Votimi, remitancat, shërbimet konsullore dhe lidhja e mërgatës me vendin.', 'draft', array['diaspora', 'diasporen', 'diaspores', 'mergata', 'mergimtar', 'mergimtaret', 'remitanca', 'remitancat', 'konsullata']::text[], array['ambasada']::text[], '{}'::text[])
on conflict (slug) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('diaspora', date '1990-01-01', 'year', 'Vitet 1990', 'Fillimet',
        'Vala e madhe e largimit', 'Gjatë viteve nentëdhjetë, qindra mijë kosovarë largohen drejt Zvicrës, Gjermanisë, Austrisë dhe vendeve nordike, si për arsye politike ashtu edhe ekonomike.', 'Harta e sotme e diasporës, dhe rrjedhimisht e remitancave, u vizatua në atë dhjetëvjeçar.', 'draft', 'hand-written (pre-pipeline)', 'vala-e-madhe-e-largimit')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('diaspora', date '1999-01-01', 'year', '1999', 'Solidariteti',
        'Fondi i diasporës gjatë luftës', 'Diaspora financon në mënyrë masive strukturat civile dhe ndihmen humanitare gjatë luftës dhe menjëherë pas saj.', 'Kjo periudhë krijoi pritshmërinë, ende të gjallë, se mërgata mbron vendin kur institucionet nuk munden.', 'draft', 'hand-written (pre-pipeline)', 'fondi-i-diaspores-gjate-luftes')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_topics (slug, title, blurb, status, anchors, signals, excludes)
values ('trump-dhe-ballkani', 'Trump dhe Ballkani', 'Politika amerikane ndaj Kosovës dhe rajonit nën administratën Trump.', 'draft', array['trump', 'trumpi', 'trumpit', 'shtepia e bardhe', 'administrata amerikane']::text[], array['uashington', 'shba']::text[], '{}'::text[])
on conflict (slug) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('trump-dhe-ballkani', date '2018-01-01', 'year', '2018–2019', 'Ndryshimi',
        'Uashingtoni merr rol të drejtpërdrejtë', 'Administrata amerikane emëron të dërguar të posaçëm për Ballkanin dhe nis një kanal negociimi paralel me atë të Brukselit, me fokus te marrëveshjet ekonomike.', 'Nga ky moment Prishtina dhe Beogradi negociojnë në dy tavolina njeherësh, jo gjithnjë me të njëjtat kushte.', 'draft', 'hand-written (pre-pipeline)', 'uashingtoni-merr-rol-te-drejtperdrejte')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('trump-dhe-ballkani', date '2020-09-04', 'day', '4 shtator 2020', 'Uashington',
        'Marrëveshjet e Uashingtonit nënshkruhen në Shtëpinë e Bardhë', 'Kosova dhe Serbia nënshkruajnë veçmas dokumente për normalizim ekonomik, në një ceremoni në Zyrën Ovale.', 'Modeli i ndërmjetësimit amerikan, i shpejtë dhe i drejtpërdrejtë, kthehet si pikë referimi sa herë ndryshon administrata.', 'draft', 'hand-written (pre-pipeline)', 'marreveshjet-e-uashingtonit-nenshkruhen-ne-shtepine-e-bardhe')
on conflict (topic_slug, dedupe_key) do nothing;

insert into public.dosje_milestones
       (topic_slug, event_date, date_precision, display_date, tag, title, summary, why, status, drafted_by, dedupe_key)
values ('trump-dhe-ballkani', date '2025-01-01', 'year', '2025', 'Rikthimi',
        'Administrata e re dhe pritjet në rajon', 'Rikthimi i administratës Trump rihap pyetjen se sa do të angazhohet Uashingtoni në Ballkan dhe me çfarë kushtesh.', 'Për Kosovën, mbështetja amerikane ka qenë historikisht garancia kryesore e sigurisë, prandaj çdo ndryshim toni ndiqet nga afer.', 'draft', 'hand-written (pre-pipeline)', 'administrata-e-re-dhe-pritjet-ne-rajon')
on conflict (topic_slug, dedupe_key) do nothing;

-- Not seeded — these carry no placeable date and need one before they can be
-- reviewed:
--   diaspora: Remitancat si shtyllë e ekonomisë (date "Në vijim")
--   diaspora: Vala verore e kthimit (date "Vera")
--   diaspora: Votimi nga jashtë vendit (date "Në vijim")
